import { Math as MathTex, PageBreak } from '@/components/shared';

export const derivativeApplicationExplanations: Record<string, React.ReactNode> = {
  'dt1w-1': <><p className="mt-2">求斜率：<MathTex tex="f'(x)=2x" />，<MathTex tex="f'(2)=4" />；求切点纵坐标：<MathTex tex="f(2)=4" />。套点斜式 <MathTex tex="y-4=4(x-2)" />，化简得 <MathTex tex="y=4x-4" />。</p></>,
  'dt1w-2': <><p className="mt-2">求斜率：<MathTex tex="f'(x)=\dfrac{1}{x}" />，<MathTex tex="f'(e)=\dfrac{1}{e}" />；求切点纵坐标：<MathTex tex="f(e)=\ln e=1" />。套点斜式 <MathTex tex="y-1=\dfrac{1}{e}(x-e)" />，化简得 <MathTex tex="y=\dfrac{x}{e}" />。</p></>,
  'dt1p-1': <><p className="mt-2">切点已经给出 <MathTex tex="(1,1)" />，只需算斜率：<MathTex tex="f'(x)=3x^2" />，<MathTex tex="f'(1)=3" />。点斜式 <MathTex tex="y-1=3(x-1)" />，化简得 <MathTex tex="y=3x-2" />。</p></>,
  'dt1p-2': <><p className="mt-2"><MathTex tex="f'(x)=e^x" />，<MathTex tex="f'(0)=1" />；切点纵坐标 <MathTex tex="f(0)=1" />。点斜式 <MathTex tex="y-1=1\cdot(x-0)" />，化简得 <MathTex tex="y=x+1" />。</p></>,
  'dt1p-3': <><p className="mt-2"><MathTex tex="f'(x)=\cos x" />，<MathTex tex="f'(0)=1" />；切点纵坐标 <MathTex tex="f(0)=0" />。点斜式 <MathTex tex="y-0=1\cdot(x-0)" />，化简得 <MathTex tex="y=x" />。</p></>,
  'dt1p-4': <><p className="mt-2">先改写 <MathTex tex="f(x)=x^{-1}" />，得 <MathTex tex="f'(x)=-x^{-2}=-\dfrac{1}{x^2}" />，<MathTex tex="f'(1)=-1" />；切点纵坐标 <MathTex tex="f(1)=1" />。点斜式 <MathTex tex="y-1=-1\cdot(x-1)" />，化简得 <MathTex tex="y=-x+2" />。</p></>,
  'dt2w-1': <><p className="mt-2">设切点 <MathTex tex="(t,t^2)" />，代 <MathTex tex="(3,8)" />：<MathTex tex="8-t^2=2t(3-t)=6t-2t^2" />，化简 <MathTex tex="t^2-6t+8=0" />，即 <MathTex tex="(t-2)(t-4)=0" />。<br />① <MathTex tex="t=2" />：切点 <MathTex tex="(2,4)" />，斜率 <MathTex tex="4" />，切线 <MathTex tex="y-4=4(x-2)" />，化简 <MathTex tex="y=4x-4" />。<br />② <MathTex tex="t=4" />：切点 <MathTex tex="(4,16)" />，斜率 <MathTex tex="8" />，切线 <MathTex tex="y-16=8(x-4)" />，化简 <MathTex tex="y=8x-16" />。</p></>,
  'dt2w-2': <><p className="mt-2">设切点 <MathTex tex="(t,e^t)" />，斜率 <MathTex tex="e^t" />，切线 <MathTex tex="y-e^t=e^t(x-t)" />。代 <MathTex tex="(0,0)" />：<MathTex tex="-e^t=e^t(0-t)=-te^t" />，两边除以 <MathTex tex="e^t" />（<MathTex tex="e^t>0" />）得 <MathTex tex="t=1" />。切点 <MathTex tex="(1,e)" />，斜率 <MathTex tex="e" />，切线 <MathTex tex="y-e=e(x-1)" />，化简得 <MathTex tex="y=ex" />。</p></>,
  'dt2p-1': <><p className="mt-2">设切点 <MathTex tex="(t,t^2)" />，代 <MathTex tex="(0,-4)" />：<MathTex tex="-4-t^2=2t(0-t)=-2t^2" />，化简 <MathTex tex="t^2=4" />，即 <MathTex tex="t=\pm 2" />。<br />① <MathTex tex="t=2" />：切点 <MathTex tex="(2,4)" />，斜率 <MathTex tex="4" />，切线 <MathTex tex="y-4=4(x-2)" />，化简 <MathTex tex="y=4x-4" />。<br />② <MathTex tex="t=-2" />：切点 <MathTex tex="(-2,4)" />，斜率 <MathTex tex="-4" />，切线 <MathTex tex="y-4=-4(x+2)" />，化简 <MathTex tex="y=-4x-4" />。</p></>,
  'dt2p-2': <><p className="mt-2">设切点 <MathTex tex="(t,\ln t)" />，斜率 <MathTex tex="\dfrac{1}{t}" />，切线 <MathTex tex="y-\ln t=\dfrac{1}{t}(x-t)" />。代 <MathTex tex="(0,0)" />：<MathTex tex="-\ln t=\dfrac{1}{t}(0-t)=-1" />，即 <MathTex tex="\ln t=1" />，解得 <MathTex tex="t=e" />。<br />切点 <MathTex tex="(e,1)" />，斜率 <MathTex tex="\dfrac{1}{e}" />，切线 <MathTex tex="y-1=\dfrac{1}{e}(x-e)" />，化简得 <MathTex tex="y=\dfrac{x}{e}" />。</p></>,
  'dt2p-3': <><p className="mt-2">设切点 <MathTex tex="(t,t^3)" />，代 <MathTex tex="(2,0)" />：<MathTex tex="0-t^3=3t^2(2-t)=6t^2-3t^3" />，化简 <MathTex tex="2t^3-6t^2=0" />，即 <MathTex tex="t^2(2t-6)=0" />，<MathTex tex="t=0" /> 或 <MathTex tex="t=3" />。<br />① <MathTex tex="t=0" />：切点 <MathTex tex="(0,0)" />，斜率 <MathTex tex="0" />，切线 <MathTex tex="y=0" />。<br />② <MathTex tex="t=3" />：切点 <MathTex tex="(3,27)" />，斜率 <MathTex tex="27" />，切线 <MathTex tex="y-27=27(x-3)" />，化简 <MathTex tex="y=27x-54" />。</p></>,
  'dt2p-4': <><p className="mt-2">求导用乘积法则：<MathTex tex="f'(x)=e^x+xe^x=(1+x)e^x" />。设切点 <MathTex tex="(t,te^t)" />，斜率 <MathTex tex="(1+t)e^t" />。<br />切线：<MathTex tex="y-te^t=(1+t)e^t(x-t)" />。代 <MathTex tex="(0,0)" />：<MathTex tex="-te^t=-t(1+t)e^t" />。<br />移项提取公因式：<MathTex tex="te^t\bigl[(1+t)-1\bigr]=0" />，即 <MathTex tex="t^2 e^t=0" />。因 <MathTex tex="e^t>0" />，所以 <MathTex tex="t=0" />。<br />切点 <MathTex tex="(0,0)" />，斜率 <MathTex tex="(1+0)e^0=1" />，切线 <MathTex tex="y=x" />。</p></>,
  'dt3w-1': <><p className="mt-2">由切线 <MathTex tex="y=4x-3" /> 知斜率 <MathTex tex="k=4" />。求导 <MathTex tex="f'(x)=2x" />，由 <MathTex tex="f'(t)=2t=4" /> 得 <MathTex tex="t=2" />。切点纵坐标 <MathTex tex="f(2)=4+a" />，又切点在切线上：<MathTex tex="4+a=4\cdot 2-3=5" />，所以 <MathTex tex="a=1" />。</p></>,
  'dt3w-2': <><p className="mt-2">求导 <MathTex tex="f'(x)=2ax" />，由 <MathTex tex="f'(1)=2a=2" /> 直接得 <MathTex tex="a=1" />。</p></>,
  'dt3p-1': <><p className="mt-2">由切线 <MathTex tex="y=3x+2" /> 知斜率 <MathTex tex="k=3" />。求导 <MathTex tex="f'(x)=3x^2" />，由 <MathTex tex="3t^2=3" /> 得 <MathTex tex="t=\pm 1" />。<br />① <MathTex tex="t=1" />：切点纵坐标 <MathTex tex="f(1)=1+a" />，又在切线上 <MathTex tex="1+a=3+2=5" />，得 <MathTex tex="a=4" />。<br />② <MathTex tex="t=-1" />：<MathTex tex="f(-1)=-1+a" />，又 <MathTex tex="-1+a=-3+2=-1" />，得 <MathTex tex="a=0" />。<br />所以 <MathTex tex="a=0" /> 或 <MathTex tex="a=4" />。</p></>,
  'dt3p-2': <><p className="mt-2">由切线 <MathTex tex="y=2x+5" /> 知 <MathTex tex="k=2" />。求导 <MathTex tex="f'(x)=(e^x+x+a)'=e^x+1" />。<br />设切点 <MathTex tex="(t,\,f(t))" />，由 <MathTex tex="f'(t)=e^t+1=2" /> 得 <MathTex tex="e^t=1" />，所以 <MathTex tex="t=0" />。<br />切点纵坐标 <MathTex tex="f(0)=e^0+0+a=1+a" />，切点 <MathTex tex="(0,\,1+a)" /> 代入切线：<MathTex tex="1+a=2\cdot 0+5=5" />，所以 <MathTex tex="a=4" />。</p></>,
  'dt3p-3': <><p className="mt-2">切线 <MathTex tex="x-y+1=0" /> 即 <MathTex tex="y=x+1" />，斜率 <MathTex tex="k=1" />。<br />① 斜率方程：<MathTex tex="f'(x)=3x^2+a" />，<MathTex tex="f'(0)=a=1" />。<br />② 切点 <MathTex tex="(0,b)" /> 在切线上：<MathTex tex="b=0+1=1" />。<br />所以 <MathTex tex="a=1,\,b=1" />。</p></>,
  'dt3p-5': <><p className="mt-2">由切线 <MathTex tex="y=2x-3" /> 知 <MathTex tex="k=2" />。求导 <MathTex tex="f'(x)=2x" />，由 <MathTex tex="f'(t)=2t=2" /> 得 <MathTex tex="t=1" />。<br />切点纵坐标 <MathTex tex="f(1)=1+a" />，切点 <MathTex tex="(1,\,1+a)" /> 代入切线：<MathTex tex="1+a=2-3=-1" />，所以 <MathTex tex="a=-2" />。</p></>,
  'dt4w-1': <><p className="mt-2"><strong>⚠️ 陷阱</strong>：<MathTex tex="\cos\dfrac{\pi}{3}" /> 是<strong>常数</strong>（值为 <MathTex tex="\dfrac{1}{2}" />），不是函数，求导为 <MathTex tex="0" />，<strong>不能写成 </strong><MathTex tex="-\sin\dfrac{\pi}{3}" />。<br /><strong>第一步（1.1）算切线</strong>：<MathTex tex="f(x)=\dfrac{1}{2}x^2+x" />，<MathTex tex="f'(x)=x+1" />，<MathTex tex="f'(0)=1" />，切线 <MathTex tex="y-0=1\cdot(x-0)" />，即 <MathTex tex="y=x" />。<br /><strong>第二步（1.3）反求 <MathTex tex="a" /></strong>：设 <MathTex tex="g(x)=\ln x+a" /> 切点 <MathTex tex="(t,\,\ln t+a)" />，<MathTex tex="g'(t)=\dfrac{1}{t}=1" />，<MathTex tex="t=1" />。切点纵坐标 <MathTex tex="\ln 1+a=a" />，切点 <MathTex tex="(1,\,a)" /> 代入切线 <MathTex tex="y=x" /> 得 <MathTex tex="a=1" />。</p></>,
  'dt4p-1': <><p className="mt-2"><strong>第一步</strong>：<MathTex tex="f'(x)=e^x" />，<MathTex tex="f'(0)=1" />，切线 <MathTex tex="y-1=1\cdot(x-0)" />，即 <MathTex tex="y=x+1" />。<br /><strong>第二步</strong>：设 <MathTex tex="g(x)=ax^2" /> 切点 <MathTex tex="(t,\,at^2)" />，<MathTex tex="g'(t)=2at=1" />，<MathTex tex="t=\dfrac{1}{2a}" />。切点纵坐标 <MathTex tex="at^2=\dfrac{1}{4a}" />，代入 <MathTex tex="y=x+1" />：<MathTex tex="\dfrac{1}{4a}=\dfrac{1}{2a}+1" />。两边乘 <MathTex tex="4a" />：<MathTex tex="1=2+4a" />，所以 <MathTex tex="a=-\dfrac{1}{4}" />。</p></>,
  'dt4p-2': <><p className="mt-2">设 <MathTex tex="(m,\,m^2+1)" /> 与 <MathTex tex="(t,\,t^2+4t+1)" />。<br /><strong>斜率</strong>：<MathTex tex="2m=2t+4" />，<MathTex tex="m=t+2" />。<br /><strong>截距</strong>：<MathTex tex="f" /> 截距 <MathTex tex="m^2+1-2m^2=1-m^2" />；<MathTex tex="g" /> 截距 <MathTex tex="(t^2+4t+1)-t(2t+4)=1-t^2" />。由 <MathTex tex="1-m^2=1-t^2" /> 得 <MathTex tex="m^2=t^2" />，<MathTex tex="m=t" /> 与 <MathTex tex="m=t+2" /> 矛盾，故 <MathTex tex="m=-t" />，代入 <MathTex tex="m=t+2" /> 得 <MathTex tex="t=-1" />，<MathTex tex="m=1" />。<br />切点 <MathTex tex="(1,\,2)" />，斜率 <MathTex tex="2m=2" />，切线 <MathTex tex="y-2=2(x-1)" />，即 <strong><MathTex tex="y=2x" /></strong>。</p></>,
  'dt4p-3': <><p className="mt-2">设 <MathTex tex="(m,\,m^2)" /> 与 <MathTex tex="(t,\,-t^2+4t-4)" />。<br /><strong>斜率</strong>：<MathTex tex="2m=-2t+4" />，<MathTex tex="m=2-t" />。<br /><strong>截距</strong>：<MathTex tex="-m^2=g(t)-tg'(t)=t^2-4" />，得 <MathTex tex="-m^2=t^2-4" />，即 <MathTex tex="(2-t)^2=4-t^2" />，化简 <MathTex tex="2t^2-4t=0" />，<MathTex tex="t=0" /> 或 <MathTex tex="t=2" />。<br />① <MathTex tex="t=0,\,m=2" />：切线 <MathTex tex="y=4x-4" />。<br />② <MathTex tex="t=2,\,m=0" />：切线 <MathTex tex="y=0" />。<br />共两条公切线 <MathTex tex="y=0" /> 和 <MathTex tex="y=4x-4" />。</p></>,
  'dt4p-4': <><p className="mt-2">设 <MathTex tex="(m,\,m^2)" /> 与 <MathTex tex="(t,\,-t^2+2t+a)" />。<br /><strong>斜率</strong>：<MathTex tex="2m=-2t+2" />，<MathTex tex="m=1-t" />。<br /><strong>截距</strong>：<MathTex tex="g(t)-tg'(t)=-t^2+2t+a-t(-2t+2)=t^2+a" />。由 <MathTex tex="-m^2=t^2+a" />：<MathTex tex="-(1-t)^2=t^2+a" />，化简 <MathTex tex="a=-2t^2+2t-1" />。<br />令 <MathTex tex="h(t)=-2t^2+2t-1" />，开口向下，最大值在 <MathTex tex="t=\dfrac{1}{2}" /> 取 <MathTex tex="h\!\left(\dfrac{1}{2}\right)=-\dfrac{1}{2}" />。<br />关于 <MathTex tex="t" /> 的方程 <MathTex tex="h(t)=a" /> 有 <strong>2 个不同实根</strong> 当且仅当 <MathTex tex="a<-\dfrac{1}{2}" />。每个 <MathTex tex="t" /> 对应一条公切线，所以 <MathTex tex="a<-\dfrac{1}{2}" />。</p></>,
  'dt4p-5': <><p className="mt-2">设 <MathTex tex="(m,\,m^2)" /> 与 <MathTex tex="(t,\,-t^2+a)" />。<br /><strong>斜率</strong>：<MathTex tex="2m=-2t" />，<MathTex tex="m=-t" />。<br /><strong>截距</strong>：<MathTex tex="f" /> 截距 <MathTex tex="-m^2" />；<MathTex tex="g" /> 截距 <MathTex tex="(-t^2+a)-t(-2t)=t^2+a" />。由 <MathTex tex="-m^2=t^2+a" />，代 <MathTex tex="m=-t" /> 得 <MathTex tex="2t^2=-a" />，即 <MathTex tex="t^2=-\dfrac{a}{2}" />。<br /><strong>分类讨论</strong>：<br />① <MathTex tex="a<0" />：<MathTex tex="t^2>0" />，两个不同实根，对应 <strong>2 条公切线</strong>。<br />② <MathTex tex="a=0" />：<MathTex tex="t=0" /> 重根，<strong>1 条公切线</strong>（即 <MathTex tex="x" /> 轴）。<br />③ <MathTex tex="a>0" />：<MathTex tex="t^2<0" /> 无实根，<strong>0 条公切线</strong>。</p></>,
};

export function DerivativeApplicationAnswers() {
  return (
    <section className="print-answers">
      <PageBreak label="答案与解析" />
      <h2 className="text-xl font-bold text-gray-900 mb-4">📝 3.5 导数的应用 — 答案与解析</h2>
      <div className="space-y-2 text-[0.95rem]">
        {Object.entries(derivativeApplicationExplanations).map(([id, expl]) => (
          <div key={id} className="border-b border-gray-200 pb-1">
            <span className="font-bold text-gray-800 mr-2">{id}</span>
            {expl}
          </div>
        ))}
      </div>
    </section>
  );
}
