import { Math as MathTex, PageBreak } from '@/components/shared';

export const derivativeApplication2Explanations: Record<string, React.ReactNode> = {
  // ── 1.1 求不含参函数的单调区间 ──
  'dm1w-1': <><p className="mt-2"><MathTex tex="f'(x)=6x-3x^2=3x(2-x)" />，零点 <MathTex tex="x=0,\,2" />。<br />令 <MathTex tex="f'(x)>0" />：<MathTex tex="3x(2-x)>0" />，得 <MathTex tex="0<x<2" />。<br />令 <MathTex tex="f'(x)<0" />：<MathTex tex="x<0" /> 或 <MathTex tex="x>2" />。<br /><strong>增区间</strong> <MathTex tex="(0,2)" />，<strong>减区间</strong> <MathTex tex="(-\infty,0)" /> 和 <MathTex tex="(2,+\infty)" />。</p></>,
  'dm1w-2': <><p className="mt-2"><strong>① 定义域</strong>：<MathTex tex="2x-1>0" />，得 <MathTex tex="x>\dfrac{1}{2}" />。<br /><strong>② 求导</strong>（复合函数）：<MathTex tex="f'(x)=\dfrac{2}{2x-1}" />。<br /><strong>③ 定号</strong>：在定义域 <MathTex tex="x>\dfrac{1}{2}" /> 内，分母 <MathTex tex="2x-1>0" />，所以 <MathTex tex="f'(x)>0" /> 恒成立。<br /><strong>结论</strong>：<MathTex tex="f(x)" /> 在 <MathTex tex="\left(\dfrac{1}{2},+\infty\right)" /> 上单调递增（无减区间）。<br /><span className="text-red-700"><strong>⚠️</strong> 不能写成"在 <MathTex tex="x\ne\dfrac{1}{2}" /> 上递增"——区间不能跨过定义域空缺。</span></p></>,
  'dm1p-1': <><p className="mt-2"><MathTex tex="f'(x)=3x^2-12x+9=3(x-1)(x-3)" />，零点 <MathTex tex="x=1,\,3" />。<br />令 <MathTex tex="f'(x)>0" />：<MathTex tex="x<1" /> 或 <MathTex tex="x>3" />（大于取两边）。<br />令 <MathTex tex="f'(x)<0" />：<MathTex tex="1<x<3" />（小于取中间）。<br /><strong>增区间</strong> <MathTex tex="(-\infty,1)" /> 和 <MathTex tex="(3,+\infty)" />，<strong>减区间</strong> <MathTex tex="(1,3)" />。</p></>,
  'dm1p-2': <><p className="mt-2"><MathTex tex="f'(x)=e^x-2" />。<br />令 <MathTex tex="f'(x)>0" />：<MathTex tex="e^x>2" />，即 <MathTex tex="x>\ln 2" />。<br />令 <MathTex tex="f'(x)<0" />：<MathTex tex="x<\ln 2" />。<br /><strong>增区间</strong> <MathTex tex="(\ln 2,+\infty)" />，<strong>减区间</strong> <MathTex tex="(-\infty,\ln 2)" />。</p></>,
  'dm1p-3': <><p className="mt-2">定义域 <MathTex tex="x>0" />。商法则求导：<MathTex tex="f'(x)=\dfrac{(\ln x)'\cdot x-\ln x\cdot x'}{x^2}=\dfrac{\frac{1}{x}\cdot x-\ln x}{x^2}=\dfrac{1-\ln x}{x^2}" />。<br />因为分母 <MathTex tex="x^2>0" /> 恒正（约掉），<MathTex tex="f'(x)" /> 与 <MathTex tex="1-\ln x" /> 同号。<br />令 <MathTex tex="1-\ln x>0" />：<MathTex tex="\ln x<1" />，即 <MathTex tex="x<e" />；结合 <MathTex tex="x>0" /> 得 <MathTex tex="0<x<e" />。<br />令 <MathTex tex="1-\ln x<0" />：<MathTex tex="x>e" />。<br /><strong>增区间</strong> <MathTex tex="(0,e)" />，<strong>减区间</strong> <MathTex tex="(e,+\infty)" />。</p></>,
  'dm1p-4': <><p className="mt-2">定义域 <MathTex tex="x\ne 0" />。<MathTex tex="f'(x)=1-\dfrac{1}{x^2}=\dfrac{x^2-1}{x^2}=\dfrac{(x-1)(x+1)}{x^2}" />。<br />因为分母 <MathTex tex="x^2>0" /> 恒正（约掉），<MathTex tex="f'(x)" /> 与 <MathTex tex="(x-1)(x+1)" /> 同号。<br />令 <MathTex tex="(x-1)(x+1)>0" />：<MathTex tex="x<-1" /> 或 <MathTex tex="x>1" />。<br />令 <MathTex tex="(x-1)(x+1)<0" />：<MathTex tex="-1<x<1" />；结合 <MathTex tex="x\ne 0" /> 得 <MathTex tex="-1<x<0" /> 或 <MathTex tex="0<x<1" />。<br /><strong>增区间</strong> <MathTex tex="(-\infty,-1)" /> 和 <MathTex tex="(1,+\infty)" />，<strong>减区间</strong> <MathTex tex="(-1,0)" /> 和 <MathTex tex="(0,1)" />。<br /><span className="text-red-700"><strong>⚠️</strong> 减区间分两段写，<strong>不能跨过 <MathTex tex="x=0" /></strong>（定义域空缺）。</span></p></>,

  // ── 1.2 已知单调性求参数范围 ──
  'dm2w-1': <><p className="mt-2"><strong>① 求导</strong>：<MathTex tex="f'(x)=3x^2-a" />。<br /><strong>② 转化</strong>：在 <MathTex tex="[1,+\infty)" /> 单调递增 <MathTex tex="\Leftrightarrow" /> <MathTex tex="3x^2-a\ge 0" /> 在 <MathTex tex="x\ge 1" /> 恒成立。<br /><strong>③ 分参</strong>：移项得 <MathTex tex="a\le 3x^2" /> 恒成立 <MathTex tex="\Leftrightarrow" /> <MathTex tex="a\le \min(3x^2)" />。<br /><MathTex tex="3x^2" /> 在 <MathTex tex="[1,+\infty)" /> 单调递增，最小值在左端点 <MathTex tex="x=1" /> 取到，<MathTex tex="\min=3" />。<br /><strong>结论</strong>：<MathTex tex="a\le 3" />。</p></>,
  'dm2w-2': <><p className="mt-2">定义域 <MathTex tex="x>0" />。<br /><strong>① 求导</strong>：<MathTex tex="f'(x)=a+\dfrac{2}{x}" />。<br /><strong>② 转化</strong>：在 <MathTex tex="[1,e]" /> 单调递增 <MathTex tex="\Leftrightarrow" /> <MathTex tex="a+\dfrac{2}{x}\ge 0" /> 在 <MathTex tex="x\in[1,e]" /> 恒成立。<br /><strong>③ 分参</strong>：移项得 <MathTex tex="a\ge -\dfrac{2}{x}" /> 恒成立 <MathTex tex="\Leftrightarrow" /> <MathTex tex="a\ge \max\left(-\dfrac{2}{x}\right)" />。<br /><MathTex tex="-\dfrac{2}{x}" /> 在 <MathTex tex="[1,e]" /> 上单调递增（<MathTex tex="x\uparrow" /> 时 <MathTex tex="\dfrac{2}{x}\downarrow" />，<MathTex tex="-\dfrac{2}{x}\uparrow" />），最大值在右端点 <MathTex tex="x=e" /> 取到，<MathTex tex="\max=-\dfrac{2}{e}" />。<br /><strong>结论</strong>：<MathTex tex="a\ge -\dfrac{2}{e}" />。</p></>,
  'dm2w-3': <><p className="mt-2"><strong>① 求导</strong>：<MathTex tex="f'(x)=e^x-a" />。<br /><strong>② 转化</strong>：在 <MathTex tex="[\ln 2,\ln 3]" /> 单调递增 <MathTex tex="\Leftrightarrow" /> <MathTex tex="e^x-a\ge 0" /> 恒成立。<br /><strong>③ 分参</strong>：<MathTex tex="a\le e^x" /> 恒成立 <MathTex tex="\Leftrightarrow" /> <MathTex tex="a\le \min(e^x)" />。<br /><MathTex tex="e^x" /> 在 <MathTex tex="[\ln 2,\ln 3]" /> 单调递增，最小值在左端点 <MathTex tex="x=\ln 2" /> 取到，<MathTex tex="\min=e^{\ln 2}=2" />。<br /><strong>结论</strong>：<MathTex tex="a\le 2" />。</p></>,
  'dm2p-1': <><p className="mt-2">定义域 <MathTex tex="x\ne 0" />。<br /><strong>① 求导</strong>：<MathTex tex="f'(x)=2x-\dfrac{a}{x^2}=\dfrac{2x^3-a}{x^2}" />。<br /><strong>② 转化</strong>：在 <MathTex tex="[2,+\infty)" /> 单调递增 <MathTex tex="\Leftrightarrow" /> <MathTex tex="\dfrac{2x^3-a}{x^2}\ge 0" /> 恒成立。<br />分母 <MathTex tex="x^2>0" /> 恒正可约，等价于 <MathTex tex="2x^3-a\ge 0" /> 恒成立。<br /><strong>③ 分参</strong>：<MathTex tex="a\le 2x^3" /> 恒成立 <MathTex tex="\Leftrightarrow" /> <MathTex tex="a\le \min(2x^3)" />。<br /><MathTex tex="2x^3" /> 在 <MathTex tex="[2,+\infty)" /> 单调递增，最小值在左端点 <MathTex tex="x=2" /> 取到，<MathTex tex="\min=16" />。<br /><strong>结论</strong>：<MathTex tex="a\le 16" />。</p></>,
  'dm2p-2': <><p className="mt-2"><strong>① 求导</strong>：<MathTex tex="f'(x)=3x^2+2ax+3" />。<br /><strong>② 转化</strong>：在 <MathTex tex="\mathbb{R}" /> 单调递增 <MathTex tex="\Leftrightarrow" /> <MathTex tex="3x^2+2ax+3\ge 0" /> 在 <MathTex tex="\mathbb{R}" /> 恒成立。<br /><strong>③ <MathTex tex="\Delta" /> 法</strong>：参数 <MathTex tex="a" /> 与 <MathTex tex="x" /> 纠缠分不开（一次项系数含 <MathTex tex="a" />），用 <MathTex tex="\Delta" /> 法。二次开口<strong>向上</strong>（<MathTex tex="A=3>0" />）✓，恒 <MathTex tex="\ge 0" /> <MathTex tex="\Leftrightarrow" /> <MathTex tex="\Delta\le 0" />。<br /><MathTex tex="\Delta=B^2-4AC=(2a)^2-4\cdot 3\cdot 3=4a^2-36\le 0" />，得 <MathTex tex="a^2\le 9" />，即 <MathTex tex="-3\le a\le 3" />。<br /><strong>结论</strong>：<MathTex tex="-3\le a\le 3" />。</p></>,
  'dm2p-3': <><p className="mt-2">定义域 <MathTex tex="x>0" />。<br /><strong>① 求导</strong>：<MathTex tex="f'(x)=\dfrac{1}{x}+2ax-2" />。<br /><strong>② 通分整理</strong>：<MathTex tex="f'(x)=\dfrac{2ax^2-2x+1}{x}" />。在 <MathTex tex="[1,e]" /> 上分母 <MathTex tex="x>0" /> 恒正，可约。要求 <MathTex tex="2ax^2-2x+1\ge 0" /> 在 <MathTex tex="[1,e]" /> 恒成立。<br /><strong>③ 分参</strong>：移项 <MathTex tex="2ax^2\ge 2x-1" />。因 <MathTex tex="x\in[1,e]" /> 时 <MathTex tex="2x^2>0" />，两边同除得 <MathTex tex="a\ge \dfrac{2x-1}{2x^2}" /> 恒成立 <MathTex tex="\Leftrightarrow" /> <MathTex tex="a\ge \max g(x)" />，其中 <MathTex tex="g(x)=\dfrac{2x-1}{2x^2}=\dfrac{1}{x}-\dfrac{1}{2x^2}" />。<br /><strong>④ 求 <MathTex tex="g(x)" /> 最大值</strong>：再求导 <MathTex tex="g'(x)=-\dfrac{1}{x^2}+\dfrac{1}{x^3}=\dfrac{1-x}{x^3}" />。在 <MathTex tex="[1,e]" /> 上 <MathTex tex="x\ge 1" /> 时 <MathTex tex="1-x\le 0" />，故 <MathTex tex="g'(x)\le 0" />，<MathTex tex="g" /> 单调递减，最大值在左端点 <MathTex tex="x=1" /> 取到，<MathTex tex="\max g=g(1)=\dfrac{1}{2}" />。<br /><strong>结论</strong>：<MathTex tex="a\ge \dfrac{1}{2}" />。</p></>,

  // ── 1.3 存在单调子区间求参 ──
  'dm3p-1': <><p className="mt-2"><strong>① 求导</strong>：<MathTex tex="f'(x)=3x^2-a" />。<br /><strong>② 翻译</strong>：在 <MathTex tex="(1,2)" /> 内存在递减区间 <MathTex tex="\Leftrightarrow" /> <MathTex tex="f'(x)<0" /> 在 <MathTex tex="(1,2)" /> 内<strong>有解</strong>，移项得 <MathTex tex="a>3x^2" /> 在 <MathTex tex="(1,2)" /> 内有解。<br /><strong>③ 分参</strong>：<MathTex tex="a>3x^2" /> 有解 <MathTex tex="\Leftrightarrow" /> <MathTex tex="a>\min(3x^2)" />（<strong>有解 → 取最小值</strong>）。<br /><MathTex tex="3x^2" /> 在 <MathTex tex="(1,2)" /> 上单调递增，代入两端 <MathTex tex="3" />、<MathTex tex="12" />，最小值 <MathTex tex="3" />。<br /><strong>结论</strong>：<MathTex tex="a>3" />。</p></>,
  'dm3p-2': <><p className="mt-2">定义域 <MathTex tex="x>0" />。<strong>① 求导</strong>：<MathTex tex="f'(x)=a-\dfrac{1}{x}" />。<br /><strong>② 翻译</strong>：在 <MathTex tex="(1,e)" /> 内存在递减区间 <MathTex tex="\Leftrightarrow" /> <MathTex tex="f'(x)<0" /> 在 <MathTex tex="(1,e)" /> 内<strong>有解</strong>，移项得 <MathTex tex="a<\dfrac{1}{x}" /> 在 <MathTex tex="(1,e)" /> 内有解。<br /><strong>③ 分参</strong>：<MathTex tex="a<\dfrac{1}{x}" /> 有解 <MathTex tex="\Leftrightarrow" /> <MathTex tex="a<\max\dfrac{1}{x}" />（<strong>有解 → 取最大值</strong>）。<br /><MathTex tex="\dfrac{1}{x}" /> 在 <MathTex tex="(1,e)" /> 上单调递减，代入两端 <MathTex tex="1" />、<MathTex tex="\dfrac{1}{e}" />，最大值 <MathTex tex="1" />。<br /><strong>结论</strong>：<MathTex tex="a<1" />。</p></>,
  'dm3p-3': <><p className="mt-2"><strong>① 求导</strong>：<MathTex tex="f'(x)=e^x+a" />。<br /><strong>② 翻译</strong>：在 <MathTex tex="(0,\ln 2)" /> 内存在递减区间 <MathTex tex="\Leftrightarrow" /> <MathTex tex="f'(x)<0" /> 在 <MathTex tex="(0,\ln 2)" /> 内<strong>有解</strong>，移项得 <MathTex tex="a<-e^x" /> 在 <MathTex tex="(0,\ln 2)" /> 内有解。<br /><strong>③ 分参</strong>：<MathTex tex="a<-e^x" /> 有解 <MathTex tex="\Leftrightarrow" /> <MathTex tex="a<\max(-e^x)" />（<strong>有解 → 取最大值</strong>）。<br /><MathTex tex="-e^x" /> 在 <MathTex tex="(0,\ln 2)" /> 上单调递减，代入两端 <MathTex tex="-e^0=-1" />、<MathTex tex="-e^{\ln 2}=-2" />，最大值 <MathTex tex="-1" />。<br /><strong>结论</strong>：<MathTex tex="a<-1" />。</p></>,
  'dm3p-4': <><p className="mt-2">定义域 <MathTex tex="x\ne 0" />。<strong>① 求导</strong>：<MathTex tex="f'(x)=2x-\dfrac{a}{x^2}=\dfrac{2x^3-a}{x^2}" />。<br /><strong>② 翻译</strong>：在 <MathTex tex="(1,2)" /> 内存在递增区间 <MathTex tex="\Leftrightarrow" /> <MathTex tex="f'(x)>0" /> 在 <MathTex tex="(1,2)" /> 内<strong>有解</strong>。<br />分母 <MathTex tex="x^2>0" /> 恒正可约，<MathTex tex="f'>0\Leftrightarrow 2x^3-a>0" />，移项得 <MathTex tex="a<2x^3" /> 在 <MathTex tex="(1,2)" /> 内有解。<br /><strong>③ 分参</strong>：<MathTex tex="a<2x^3" /> 有解 <MathTex tex="\Leftrightarrow" /> <MathTex tex="a<\max(2x^3)" />（<strong>有解 → 取最大值</strong>）。<br /><MathTex tex="2x^3" /> 在 <MathTex tex="(1,2)" /> 上单调递增，代入两端 <MathTex tex="2" />、<MathTex tex="16" />，最大值 <MathTex tex="16" />。<br /><strong>结论</strong>：<MathTex tex="a<16" />。</p></>,
  'dm3p-5': <><p className="mt-2"><strong>① 求导</strong>：<MathTex tex="f'(x)=a+\cos x" />。<br /><strong>② 翻译</strong>：在 <MathTex tex="(0,\pi)" /> 内存在递减区间 <MathTex tex="\Leftrightarrow" /> <MathTex tex="f'(x)<0" /> 在 <MathTex tex="(0,\pi)" /> 内<strong>有解</strong>，移项得 <MathTex tex="a<-\cos x" /> 在 <MathTex tex="(0,\pi)" /> 内有解。<br /><strong>③ 分参</strong>：<MathTex tex="a<-\cos x" /> 有解 <MathTex tex="\Leftrightarrow" /> <MathTex tex="a<\max(-\cos x)" />（<strong>有解 → 取最大值</strong>）。<br /><MathTex tex="\cos x" /> 在 <MathTex tex="(0,\pi)" /> 上取值 <MathTex tex="(-1,1)" />，故 <MathTex tex="-\cos x" /> 取值 <MathTex tex="(-1,1)" />，最大值 <MathTex tex="1" />（<MathTex tex="x\to\pi" /> 时趋近）。<br /><strong>结论</strong>：<MathTex tex="a<1" />。</p></>,

  // ── 1.4 含参讨论单调性 ──
  'dm4-1': <><p className="mt-2">定义域 <MathTex tex="x>0" />。<strong>① 求导</strong>：<MathTex tex="f'(x)=a-\dfrac{2}{x}=\dfrac{ax-2}{x}" />。分母 <MathTex tex="x>0" /> 恒正可约，看分子 <MathTex tex="ax-2" />。<br /><strong>② 按 <MathTex tex="a" /> 分类</strong>：<br /><strong>情况一</strong> <MathTex tex="a\le 0" />：<MathTex tex="ax\le 0<2" />，<MathTex tex="ax-2<0" /> 恒成立 → <MathTex tex="f'(x)<0" /> → <MathTex tex="f(x)" /> 在 <MathTex tex="(0,+\infty)" /> 单调<strong>递减</strong>。<br /><strong>情况二</strong> <MathTex tex="a>0" />：<MathTex tex="ax-2=0" /> 解得 <MathTex tex="x=\dfrac{2}{a}" />。<br /><span className="pl-4">当 <MathTex tex="0<x<\dfrac{2}{a}" />，<MathTex tex="ax-2<0" />，<MathTex tex="f'<0" /> → <strong>减</strong>；</span><br /><span className="pl-4">当 <MathTex tex="x>\dfrac{2}{a}" />，<MathTex tex="ax-2>0" />，<MathTex tex="f'>0" /> → <strong>增</strong>。<br /></span><strong>综上</strong>：<MathTex tex="a\le 0" /> 时减区间 <MathTex tex="(0,+\infty)" />；<MathTex tex="a>0" /> 时减区间 <MathTex tex="\left(0,\dfrac{2}{a}\right)" />，增区间 <MathTex tex="\left(\dfrac{2}{a},+\infty\right)" />。</p></>,
  'dm4-2': <><p className="mt-2"><strong>① 求导</strong>：<MathTex tex="f'(x)=x^2-2ax=x(x-2a)" />，零点 <MathTex tex="x=0" /> 和 <MathTex tex="x=2a" />。<br /><strong>② 按 <MathTex tex="a" /> 符号分类（决定两根大小）</strong>：<br /><strong>情况一</strong> <MathTex tex="a>0" />：<MathTex tex="0<2a" />，三段：<MathTex tex="(-\infty,0)" /> 增、<MathTex tex="(0,2a)" /> 减、<MathTex tex="(2a,+\infty)" /> 增。<br /><strong>情况二</strong> <MathTex tex="a=0" />：<MathTex tex="f'(x)=x^2\ge 0" />（仅 <MathTex tex="x=0" /> 处为孤立零点，不变号）→ <MathTex tex="f(x)" /> 在 <MathTex tex="\mathbb{R}" /> 上单调<strong>递增</strong>。<br /><strong>情况三</strong> <MathTex tex="a<0" />：<MathTex tex="2a<0" />，三段：<MathTex tex="(-\infty,2a)" /> 增、<MathTex tex="(2a,0)" /> 减、<MathTex tex="(0,+\infty)" /> 增。<br /><strong>综上</strong>：<MathTex tex="a>0" /> 时增区间 <MathTex tex="(-\infty,0),(2a,+\infty)" />，减区间 <MathTex tex="(0,2a)" />；<MathTex tex="a=0" /> 时 <MathTex tex="\mathbb{R}" /> 上单增；<MathTex tex="a<0" /> 时增区间 <MathTex tex="(-\infty,2a),(0,+\infty)" />，减区间 <MathTex tex="(2a,0)" />。</p></>,
  'dm4-3': <><p className="mt-2"><strong>① 求导</strong>：<MathTex tex="f'(x)=3x^2-6ax=3x(x-2a)" />。在 <MathTex tex="[1,2]" /> 上 <MathTex tex="x>0" />（恒正可约），所以 <MathTex tex="f'" /> 与 <MathTex tex="x-2a" /> 同号。<br /><strong>② 按零点 <MathTex tex="2a" /> 与区间 <MathTex tex="[1,2]" /> 的位置分类</strong>：<br /><strong>情况一</strong> <MathTex tex="2a\le 1" />（即 <MathTex tex="a\le \dfrac{1}{2}" />）：在 <MathTex tex="[1,2]" /> 上 <MathTex tex="x-2a\ge 0" /> → <MathTex tex="f'\ge 0" /> → <strong>单调递增</strong>。<br /><strong>情况二</strong> <MathTex tex="1<2a<2" />（即 <MathTex tex="\dfrac{1}{2}<a<1" />）：零点 <MathTex tex="2a" /> 在区间内。<MathTex tex="(1,2a)" /> 上 <MathTex tex="x-2a<0" /> → <strong>减</strong>；<MathTex tex="(2a,2)" /> 上 <MathTex tex="x-2a>0" /> → <strong>增</strong>。<br /><strong>情况三</strong> <MathTex tex="2a\ge 2" />（即 <MathTex tex="a\ge 1" />）：在 <MathTex tex="[1,2]" /> 上 <MathTex tex="x-2a\le 0" /> → <MathTex tex="f'\le 0" /> → <strong>单调递减</strong>。</p></>,
  'dm4-4': <><p className="mt-2">定义域 <MathTex tex="x>0" />。<strong>① 求导通分</strong>：<MathTex tex="f'(x)=x-a+\dfrac{1}{x}=\dfrac{x^2-ax+1}{x}" />。分母 <MathTex tex="x>0" /> 可约，看分子 <MathTex tex="g(x)=x^2-ax+1" />（开口向上，对称轴 <MathTex tex="x=\dfrac{a}{2}" />）。<br /><strong>② 按判别式 <MathTex tex="\Delta=a^2-4" /> 分类</strong>：<br /><strong>情况一</strong> <MathTex tex="\Delta\le 0" />（即 <MathTex tex="-2\le a\le 2" />）：<MathTex tex="g(x)\ge 0" /> 恒成立 → <MathTex tex="f'\ge 0" /> → 在 <MathTex tex="(0,+\infty)" /> <strong>单调递增</strong>。<br /><strong>情况二</strong> <MathTex tex="\Delta>0" /> 且 <MathTex tex="a<-2" />：两根 <MathTex tex="x_{1,2}=\dfrac{a\mp\sqrt{a^2-4}}{2}" />。由 <MathTex tex="x_1+x_2=a<0" />、<MathTex tex="x_1 x_2=1>0" />，两根都 <MathTex tex="<0" />，不在定义域内 → <MathTex tex="g(x)>0" /> 在 <MathTex tex="(0,+\infty)" /> 恒成立 → <strong>单增</strong>。<br /><strong>情况三</strong> <MathTex tex="\Delta>0" /> 且 <MathTex tex="a>2" />：两根 <MathTex tex="x_1+x_2=a>0" />、<MathTex tex="x_1 x_2=1>0" />，两根都 <MathTex tex=">0" />。三段：<MathTex tex="(0,x_1)" /> 增、<MathTex tex="(x_1,x_2)" /> 减、<MathTex tex="(x_2,+\infty)" /> 增。<br /><strong>综上</strong>：<MathTex tex="a\le 2" /> 时单增；<MathTex tex="a>2" /> 时增区间 <MathTex tex="(0,x_1),(x_2,+\infty)" />，减区间 <MathTex tex="(x_1,x_2)" />，<MathTex tex="x_{1,2}=\dfrac{a\mp\sqrt{a^2-4}}{2}" />。</p></>,
  'dm4-5': <><p className="mt-2">定义域 <MathTex tex="x>0" />。<strong>① 求导</strong>：<MathTex tex="f'(x)=\dfrac{a}{x}-2x=\dfrac{a-2x^2}{x}" />。分母 <MathTex tex="x>0" /> 可约，看分子 <MathTex tex="a-2x^2" />。<br /><strong>② 按 <MathTex tex="a" /> 分类</strong>：<br /><strong>情况一</strong> <MathTex tex="a\le 0" />：在 <MathTex tex="x>0" /> 时 <MathTex tex="2x^2>0" />，<MathTex tex="a-2x^2<0" /> 恒成立 → <MathTex tex="f'<0" /> → 在 <MathTex tex="(0,+\infty)" /> <strong>单调递减</strong>。<br /><strong>情况二</strong> <MathTex tex="a>0" />：<MathTex tex="a-2x^2=0" /> 得 <MathTex tex="x=\sqrt{\dfrac{a}{2}}" />（取正根）。<br /><span className="pl-4"><MathTex tex="0<x<\sqrt{\dfrac{a}{2}}" /> 时 <MathTex tex="a-2x^2>0" />，<MathTex tex="f'>0" /> → <strong>增</strong>；</span><br /><span className="pl-4"><MathTex tex="x>\sqrt{\dfrac{a}{2}}" /> 时 <MathTex tex="a-2x^2<0" />，<MathTex tex="f'<0" /> → <strong>减</strong>。<br /></span><strong>综上</strong>：<MathTex tex="a\le 0" /> 时减区间 <MathTex tex="(0,+\infty)" />；<MathTex tex="a>0" /> 时增区间 <MathTex tex="\left(0,\sqrt{\dfrac{a}{2}}\right)" />，减区间 <MathTex tex="\left(\sqrt{\dfrac{a}{2}},+\infty\right)" />。</p></>,
};

export function DerivativeApplication2Answers() {
  return (
    <section className="print-answers">
      <PageBreak label="答案与解析" />
      <h2 className="text-xl font-bold text-gray-900 mb-4">📝 3.6 导数应用（下） — 答案与解析</h2>
      <div className="space-y-2 text-[0.95rem]">
        {Object.entries(derivativeApplication2Explanations).map(([id, expl]) => (
          <div key={id} className="border-b border-gray-200 pb-1">
            <span className="font-bold text-gray-800 mr-2">{id}</span>
            {expl}
          </div>
        ))}
      </div>
    </section>
  );
}
