import { Math as MathTex, PageBreak } from '@/components/shared';

// 注：1.1 求不含参函数单调区间的答案已迁至 3.6.0-deriv-method-answers.tsx
export const derivativeApplication2Explanations: Record<string, React.ReactNode> = {
  // ── 0.3 不含参恒成立 · 练手 ──
  'ah03-1': <><p className="mt-2"><strong>① 求最值</strong>：记 <MathTex tex="f(x)=2x^2+1" />，开口向上，对称轴 <MathTex tex="x=0" />，最小值 <MathTex tex="f(0)=1" />。<br /><strong>② 验证</strong>：把 <MathTex tex="f_{\min}=1" /> 代入原不等式得 <MathTex tex="1\ge 0" />，<strong>成立</strong>。<br /><strong>③ 结论</strong>：<strong>恒成立</strong>。最小值 <MathTex tex="\ge 0" />，其他函数值都比 1 大，自然 <MathTex tex="\ge 0" />。</p></>,
  'ah03-2': <><p className="mt-2"><strong>① 求最值</strong>：记 <MathTex tex="f(x)=x^2+2x-3=(x+1)^2-4" />，开口向上，对称轴 <MathTex tex="x=-1" />，最小值 <MathTex tex="f(-1)=-4" />。<br /><strong>② 验证</strong>：把 <MathTex tex="f_{\min}=-4" /> 代入原不等式得 <MathTex tex="-4\ge 0" />，<strong>不成立</strong>。<br /><strong>③ 结论</strong>：<strong>不恒成立</strong>。<MathTex tex="f(x)" /> 的最小值小于 0，说明在 <MathTex tex="\mathbb{R}" /> 上并不恒成立。</p></>,

  // ── 0.8 三种方法综合练习 ──
  'ah08-1': <><p className="mt-2"><strong>Δ 法</strong>：<MathTex tex="A=1>0" /> 开口向上，要 <MathTex tex="\ge 0" /> 恒成立，需 <MathTex tex="\Delta\le 0" />。<br /><MathTex tex="\Delta=(2a)^2-4\cdot 1\cdot 4=4a^2-16\le 0" />，得 <MathTex tex="a^2\le 4" />，即 <MathTex tex="-2\le a\le 2" />。</p></>,
  'ah08-2': <><p className="mt-2"><strong>Δ 法</strong>：<MathTex tex="A=-1<0" /> 开口向下，要 <MathTex tex="\le 0" /> 恒成立，需 <MathTex tex="\Delta\le 0" />。<br /><MathTex tex="\Delta=a^2-4\cdot(-1)\cdot(-1)=a^2-4\le 0" />，得 <MathTex tex="a^2\le 4" />，即 <MathTex tex="-2\le a\le 2" />。</p></>,
  'ah08-3': <><p className="mt-2"><strong>分参法</strong>：<MathTex tex="x\in[1,2]" /> 时 <MathTex tex="x>0" />，两边除 <MathTex tex="x" /> 不翻号，得 <MathTex tex="a\le x+\dfrac{2}{x}" /> 恒成立 <MathTex tex="\Leftrightarrow" /> <MathTex tex="a\le \min\left(x+\dfrac{2}{x}\right)" />。<br />记 <MathTex tex="g(x)=x+\dfrac{2}{x}" />，求导 <MathTex tex="g'(x)=1-\dfrac{2}{x^2}" />。在 <MathTex tex="[1,2]" /> 上令 <MathTex tex="g'=0" /> 得 <MathTex tex="x=\sqrt{2}\in[1,2]" />。<br /><MathTex tex="g(1)=3" />，<MathTex tex="g(\sqrt{2})=2\sqrt{2}\approx 2.83" />，<MathTex tex="g(2)=3" />。最小值 <MathTex tex="g(\sqrt{2})=2\sqrt{2}" />。<br /><strong>结论</strong>：<MathTex tex="a\le 2\sqrt{2}" />。</p></>,
  'ah08-4': <><p className="mt-2"><strong>分参法</strong>：<MathTex tex="a" /> 已在左边且独立，直接得 <MathTex tex="a\le x+\dfrac{1}{\ln x+1}" /> 恒成立 <MathTex tex="\Leftrightarrow" /> <MathTex tex="a\le \min\left(x+\dfrac{1}{\ln x+1}\right)" />。<br />记 <MathTex tex="g(x)=x+\dfrac{1}{\ln x+1}" />，当 <MathTex tex="x=1" /> 时 <MathTex tex="g(1)=1+\dfrac{1}{\ln 1+1}=1+1=2" />。<br />可验证 <MathTex tex="g'(x)>0" /> 在 <MathTex tex="[1,e]" /> 上（<MathTex tex="g" /> 递增），最小值在左端点。<br /><strong>结论</strong>：<MathTex tex="a\le 2" />。</p></>,
  'ah08-5': <><p className="mt-2"><strong>配方法</strong>：<MathTex tex="x^2-4ax+2=(x-2a)^2-4a^2+2" />。<br />开口向上，最小值 <MathTex tex="=-4a^2+2" />。要 <MathTex tex="\ge 0" /> 恒成立，需最小值 <MathTex tex="\ge 0" />：<br /><MathTex tex="-4a^2+2\ge 0" />，即 <MathTex tex="a^2\le \dfrac{1}{2}" />，解得 <MathTex tex="-\dfrac{\sqrt{2}}{2}\le a\le \dfrac{\sqrt{2}}{2}" />。</p></>,
  'ah08-6': <><p className="mt-2"><strong>分参法</strong>：<MathTex tex="x\in[2,5]" /> 时 <MathTex tex="x>0" />，两边除 <MathTex tex="x" /> 不翻号，得 <MathTex tex="a\le \dfrac{x^2-3}{x}=x-\dfrac{3}{x}" /> 恒成立 <MathTex tex="\Leftrightarrow" /> <MathTex tex="a\le \min\left(x-\dfrac{3}{x}\right)" />。<br />记 <MathTex tex="g(x)=x-\dfrac{3}{x}" />，求导 <MathTex tex="g'(x)=1+\dfrac{3}{x^2}>0" />，在 <MathTex tex="[2,5]" /> 上递增。<br />最小值在左端点 <MathTex tex="g(2)=2-\dfrac{3}{2}=\dfrac{1}{2}" />。<br /><strong>结论</strong>：<MathTex tex="a\le \dfrac{1}{2}" />。</p></>,

  // ── 1.2 例 A 变式 ──
  'dm2va-1': <><p className="mt-2"><strong>① 求导</strong>：<MathTex tex="f'(x)=3x^2+2ax" />。<br /><strong>② 转化</strong>：在 <MathTex tex="[0,+\infty)" /> 上递增 <MathTex tex="\Leftrightarrow" /> <MathTex tex="3x^2+2ax\ge 0" /> 在 <MathTex tex="x\ge 0" /> 上恒成立。<br /><strong>③ 分参</strong>：提公因子得 <MathTex tex="x(3x+2a)\ge 0" />。当 <MathTex tex="x=0" /> 时等号自动成立；当 <MathTex tex="x>0" /> 时两边除 <MathTex tex="x" />（正数，不翻号），得 <MathTex tex="3x+2a\ge 0" />，即 <MathTex tex="2a\ge -3x" />，即 <MathTex tex="a\ge -\dfrac{3x}{2}" /> 恒成立 <MathTex tex="\Leftrightarrow" /> <MathTex tex="a\ge \max\left(-\dfrac{3x}{2}\right)" />。<br /><strong>④ 求最大值</strong>：<MathTex tex="-\dfrac{3x}{2}" /> 在 <MathTex tex="[0,+\infty)" /> 上单调递减，最大值在左端点 <MathTex tex="x=0" /> 取到，<MathTex tex="\max=0" />。<br /><strong>结论</strong>：<MathTex tex="a\ge 0" />。</p></>,
  'dm2vb-1': <><p className="mt-2">求导，得 <MathTex tex="f'(x)=3x^2-2ax+3" />。<br />由题意，<MathTex tex="f'(x)\ge 0" /> 在 <MathTex tex="\mathbb{R}" /> 上恒成立。<br />因为 <MathTex tex="A=3>0" />，所以 <MathTex tex="\Delta\le 0" />，即 <MathTex tex="(-2a)^2-4\cdot 3\cdot 3\le 0" />，化简得 <MathTex tex="a^2\le 9" />，解得 <MathTex tex="-3\le a\le 3" />。<br />故 <MathTex tex="a" /> 的取值范围为 <MathTex tex="[-3,3]" />。</p></>,
  'dm2vb-2': <><p className="mt-2">求导，得 <MathTex tex="f'(x)=-3x^2+2ax-1" />。<br />由题意，<MathTex tex="f'(x)\le 0" /> 在 <MathTex tex="\mathbb{R}" /> 上恒成立。<br />因为 <MathTex tex="A=-3<0" />，所以 <MathTex tex="\Delta\le 0" />，即 <MathTex tex="(2a)^2-4\cdot(-3)\cdot(-1)\le 0" />，化简得 <MathTex tex="a^2\le 3" />，解得 <MathTex tex="-\sqrt{3}\le a\le \sqrt{3}" />。<br />故 <MathTex tex="a" /> 的取值范围为 <MathTex tex="[-\sqrt{3},\sqrt{3}]" />。</p></>,

  'dm2vc-1': <><p className="mt-2">求导，得 <MathTex tex="f'(x)=a-\dfrac{1}{x}" />。<br />由题意，<MathTex tex="f'(x)\ge 0" /> 在 <MathTex tex="[1,e]" /> 上恒成立，即 <MathTex tex="a\ge \dfrac{1}{x}" /> 在 <MathTex tex="[1,e]" /> 上恒成立。<br />反比例函数 <MathTex tex="\dfrac{1}{x}" />（<MathTex tex="k=1>0" />）在 <MathTex tex="(0,+\infty)" /> 上单调递减，所以 <MathTex tex="\dfrac{1}{x}" /> 在 <MathTex tex="[1,e]" /> 上的最大值在左端点 <MathTex tex="x=1" /> 取到，最大值为 <MathTex tex="1" />。<br />故 <MathTex tex="a\ge 1" />，即 <MathTex tex="a" /> 的取值范围为 <MathTex tex="[1,+\infty)" />。</p></>,
  'dm2vc-2': <><p className="mt-2">求导，得 <MathTex tex="f'(x)=\dfrac{2}{x}-a" />。<br />由题意，<MathTex tex="f'(x)\le 0" /> 在 <MathTex tex="[1,e]" /> 上恒成立，即 <MathTex tex="a\ge \dfrac{2}{x}" /> 在 <MathTex tex="[1,e]" /> 上恒成立。<br />反比例函数 <MathTex tex="\dfrac{2}{x}" />（<MathTex tex="k=2>0" />）在 <MathTex tex="(0,+\infty)" /> 上单调递减，所以 <MathTex tex="\dfrac{2}{x}" /> 在 <MathTex tex="[1,e]" /> 上的最大值在左端点 <MathTex tex="x=1" /> 取到，最大值为 <MathTex tex="2" />。<br />故 <MathTex tex="a\ge 2" />，即 <MathTex tex="a" /> 的取值范围为 <MathTex tex="[2,+\infty)" />。</p></>,
  'dm2vd-1': <><p className="mt-2">求导，得 <MathTex tex="f'(x)=a-e^x" />。<br />由题意，<MathTex tex="f'(x)\le 0" /> 在 <MathTex tex="[0,\ln 2]" /> 上恒成立，即 <MathTex tex="a\le e^x" /> 在 <MathTex tex="[0,\ln 2]" /> 上恒成立。<br />记 <MathTex tex="g(x)=e^x" />，求导得 <MathTex tex="g'(x)=e^x>0" />，所以 <MathTex tex="g(x)" /> 单调递增。最小值在左端点 <MathTex tex="x=0" /> 取到，<MathTex tex="g(0)=e^0=1" />。<br />故 <MathTex tex="a\le 1" />，即 <MathTex tex="a" /> 的取值范围为 <MathTex tex="(-\infty,1]" />。</p></>,
  'dm2ve-1': <><p className="mt-2">求导，得 <MathTex tex="f'(x)=1-\dfrac{a}{x^2}=\dfrac{x^2-a}{x^2}" />。<br />由题意，<MathTex tex="f'(x)\ge 0" /> 在 <MathTex tex="[2,+\infty)" /> 上恒成立。分母 <MathTex tex="x^2>0" /> 恒正可约，等价于 <MathTex tex="x^2-a\ge 0" /> 在 <MathTex tex="[2,+\infty)" /> 上恒成立，即 <MathTex tex="a\le x^2" /> 在 <MathTex tex="[2,+\infty)" /> 上恒成立。<br />记 <MathTex tex="g(x)=x^2" />，求导得 <MathTex tex="g'(x)=2x" />。当 <MathTex tex="x\in[2,+\infty)" /> 时 <MathTex tex="2x\ge 4>0" />，所以 <MathTex tex="g(x)" /> 单调递增。最小值在左端点 <MathTex tex="x=2" /> 取到，<MathTex tex="g(2)=4" />。<br />故 <MathTex tex="a\le 4" />，即 <MathTex tex="a" /> 的取值范围为 <MathTex tex="(-\infty,4]" />。</p></>,
  'dexw-1': <><p className="mt-2"><MathTex tex="x\in[0,2]" /> 时 <MathTex tex="2x-1\in[-1,3]" />，所以 <MathTex tex="\min(2x-1)=-1" />。<br />"<MathTex tex="a>2x-1" /> 有解" 等价于 <MathTex tex="a>\min(2x-1)=-1" />，故 <MathTex tex="a\in(-1,+\infty)" />。</p></>,
  'dexw-2': <><p className="mt-2">记 <MathTex tex="g(x)=x^2-2x=(x-1)^2-1" />，对称轴 <MathTex tex="x=1\in[0,3]" />。<br />当 <MathTex tex="x=1" /> 时取最小值 <MathTex tex="g(1)=-1" />；当 <MathTex tex="x=3" /> 时取最大值 <MathTex tex="g(3)=3" />。<br />"<MathTex tex="a\le x^2-2x" /> 有解" 等价于 <MathTex tex="a\le \max(x^2-2x)=3" />，故 <MathTex tex="a\in(-\infty,3]" />。</p></>,

  'dm2ve-2': <><p className="mt-2">定义域 <MathTex tex="x>0" />。求导，得 <MathTex tex="f'(x)=2x-\dfrac{a}{x^2}-\dfrac{3}{x}=\dfrac{2x^3-3x-a}{x^2}" />。<br />由题意，<MathTex tex="f'(x)\ge 0" /> 在 <MathTex tex="[1,2]" /> 上恒成立。分母 <MathTex tex="x^2>0" /> 恒正可约，等价于 <MathTex tex="2x^3-3x-a\ge 0" /> 在 <MathTex tex="[1,2]" /> 上恒成立，即 <MathTex tex="a\le 2x^3-3x" /> 在 <MathTex tex="[1,2]" /> 上恒成立。<br />记 <MathTex tex="g(x)=2x^3-3x" />，求导得 <MathTex tex="g'(x)=6x^2-3" />。当 <MathTex tex="x\in[1,2]" /> 时 <MathTex tex="x^2\ge 1" />，所以 <MathTex tex="6x^2\ge 6>3" />，故 <MathTex tex="g'(x)>0" />，<MathTex tex="g(x)" /> 单调递增。<br />最小值在左端点 <MathTex tex="x=1" /> 取到，<MathTex tex="g(1)=2-3=-1" />。<br />故 <MathTex tex="a\le -1" />，即 <MathTex tex="a" /> 的取值范围为 <MathTex tex="(-\infty,-1]" />。</p></>,

  'dm2vd-2': <><p className="mt-2">求导，得 <MathTex tex="f'(x)=e^x+2x-a" />。<br />由题意，<MathTex tex="f'(x)\ge 0" /> 在 <MathTex tex="[0,\ln 3]" /> 上恒成立，即 <MathTex tex="a\le e^x+2x" /> 在 <MathTex tex="[0,\ln 3]" /> 上恒成立。<br />记 <MathTex tex="g(x)=e^x+2x" />，求导得 <MathTex tex="g'(x)=e^x+2>0" />，所以 <MathTex tex="g(x)" /> 单调递增。最小值在左端点 <MathTex tex="x=0" /> 取到，<MathTex tex="g(0)=e^0+0=1" />。<br />故 <MathTex tex="a\le 1" />，即 <MathTex tex="a" /> 的取值范围为 <MathTex tex="(-\infty,1]" />。</p></>,

  'dm2vc-3': <><p className="mt-2">求导，得 <MathTex tex="f'(x)=2x+\dfrac{1}{x}-a" />。<br />由题意，<MathTex tex="f'(x)\ge 0" /> 在 <MathTex tex="[1,e]" /> 上恒成立，即 <MathTex tex="a\le 2x+\dfrac{1}{x}" /> 在 <MathTex tex="[1,e]" /> 上恒成立。<br />记 <MathTex tex="g(x)=2x+\dfrac{1}{x}" />，求导得 <MathTex tex="g'(x)=2-\dfrac{1}{x^2}" />。当 <MathTex tex="x\in[1,e]" /> 时 <MathTex tex="x^2\ge 1" />，所以 <MathTex tex="\dfrac{1}{x^2}\le 1" />，故 <MathTex tex="g'(x)\ge 1>0" />，<MathTex tex="g(x)" /> 在 <MathTex tex="[1,e]" /> 上单调递增。<br />最小值在左端点 <MathTex tex="x=1" /> 取到，<MathTex tex="g(1)=2+1=3" />。<br />故 <MathTex tex="a\le 3" />，即 <MathTex tex="a" /> 的取值范围为 <MathTex tex="(-\infty,3]" />。</p></>,

  'dm2va-2': <><p className="mt-2"><strong>① 求导</strong>：<MathTex tex="f'(x)=-3x^2+a" />。<br /><strong>② 转化</strong>：在 <MathTex tex="(-1,1)" /> 上递减 <MathTex tex="\Leftrightarrow" /> <MathTex tex="-3x^2+a\le 0" /> 在 <MathTex tex="x\in(-1,1)" /> 上恒成立。<br /><strong>③ 分参</strong>：移项得 <MathTex tex="a\le 3x^2" /> 恒成立 <MathTex tex="\Leftrightarrow" /> <MathTex tex="a\le \min(3x^2)" />。<br /><strong>④ 求最小值</strong>：<MathTex tex="3x^2" /> 在 <MathTex tex="(-1,1)" /> 上，<MathTex tex="A=3>0" /> 开口向上，对称轴 <MathTex tex="x=0\in(-1,1)" />。代入得 <MathTex tex="g(0)=0" />，所以 <MathTex tex="\min(3x^2)=0" />。<br /><strong>结论</strong>：<MathTex tex="a\le 0" />。</p></>,

  // ── 1.3 例 A 变式 ──
  'dm3va-1': <><p className="mt-2"><strong>解</strong>：<MathTex tex="f'(x)=3x^2-a" />。<br />由题意，存在 <MathTex tex="x\in[-1,1]" />，使 <MathTex tex="f'(x)>0" />，即 <MathTex tex="3x^2>a" /> 在 <MathTex tex="[-1,1]" /> 上有解，故 <MathTex tex="a<(3x^2)_{\max}" />。<br />记 <MathTex tex="g(x)=3x^2" />，<MathTex tex="g" /> 开口向上，对称轴 <MathTex tex="x=0" />。当 <MathTex tex="x\in[-1,1]" /> 时，<MathTex tex="g(x)" /> 在端点 <MathTex tex="x=\pm 1" /> 取得最大值 <MathTex tex="g(\pm 1)=3" />。<br />所以 <MathTex tex="g(x)" /> 的取值范围是 <MathTex tex="[0,3]" />，故 <MathTex tex="a<3" /> 时满足题意。</p></>,

  'dm3vb-1': <><p className="mt-2"><strong>解</strong>：<MathTex tex="f'(x)=a-\dfrac{1}{x}" />。<br />由题意，<MathTex tex="f'(x)>0" /> 在 <MathTex tex="[1,e]" /> 上有解，即 <MathTex tex="a-\dfrac{1}{x}>0" />。<br />移项得 <MathTex tex="a>\dfrac{1}{x}" />，故 <MathTex tex="a>\left(\dfrac{1}{x}\right)_{\min}" />。<br />记 <MathTex tex="g(x)=\dfrac{1}{x}" />，<MathTex tex="g'(x)=-\dfrac{1}{x^2}<0" />，所以 <MathTex tex="g(x)" /> 在 <MathTex tex="[1,e]" /> 上单调递减。<br />最小值在右端点 <MathTex tex="x=e" /> 取得，<MathTex tex="g(e)=\dfrac{1}{e}" />，故 <MathTex tex="a>\dfrac{1}{e}" /> 时满足题意。</p></>,

  'dm3vb-2': <><p className="mt-2"><strong>解</strong>：<MathTex tex="f'(x)=a+\dfrac{1}{x}" />。<br />由题意，<MathTex tex="f'(x)<0" /> 在 <MathTex tex="[1,e^2]" /> 上有解，即 <MathTex tex="a+\dfrac{1}{x}<0" />。<br />移项得 <MathTex tex="a<-\dfrac{1}{x}" />，故 <MathTex tex="a<\left(-\dfrac{1}{x}\right)_{\max}" />。<br />记 <MathTex tex="g(x)=-\dfrac{1}{x}" />，<MathTex tex="g'(x)=\dfrac{1}{x^2}>0" />，所以 <MathTex tex="g(x)" /> 在 <MathTex tex="[1,e^2]" /> 上单调递增。<br />最大值在右端点 <MathTex tex="x=e^2" /> 取得，<MathTex tex="g(e^2)=-\dfrac{1}{e^2}" />，故 <MathTex tex="a<-\dfrac{1}{e^2}" /> 时满足题意。</p></>,

  'dm3vc-1': <><p className="mt-2"><strong>解</strong>：<MathTex tex="f'(x)=e^x+(x-2)e^x+a=(x-1)e^x+a" />。<br />由题意，<MathTex tex="f'(x)>0" /> 在 <MathTex tex="[0,1]" /> 上有解，即 <MathTex tex="(x-1)e^x+a>0" />。<br />移项得 <MathTex tex="a>(1-x)e^x" />，故 <MathTex tex="a>[(1-x)e^x]_{\min}" />。<br />记 <MathTex tex="g(x)=(1-x)e^x" />，求导得 <MathTex tex="g'(x)=-e^x+(1-x)e^x=-xe^x" />。当 <MathTex tex="x\in[0,1]" /> 时 <MathTex tex="x\ge 0" />，<MathTex tex="e^x>0" />，所以 <MathTex tex="g'(x)\le 0" />，<MathTex tex="g(x)" /> 在 <MathTex tex="[0,1]" /> 上单调递减。<br />最小值在右端点 <MathTex tex="x=1" /> 取得，<MathTex tex="g(1)=0" />，故 <MathTex tex="a>0" /> 时满足题意。</p></>,

  'dm3vc-2': <><p className="mt-2"><strong>解</strong>：<MathTex tex="f'(x)=e^x+(x-1)e^x+a=xe^x+a" />。<br />由题意，<MathTex tex="f'(x)<0" /> 在 <MathTex tex="[0,2]" /> 上有解，即 <MathTex tex="xe^x+a<0" />。<br />移项得 <MathTex tex="a<-xe^x" />，故 <MathTex tex="a<(-xe^x)_{\max}" />。<br />记 <MathTex tex="g(x)=-xe^x" />，求导得 <MathTex tex="g'(x)=-e^x-xe^x=-(x+1)e^x" />。当 <MathTex tex="x\in[0,2]" /> 时 <MathTex tex="x+1>0" />，<MathTex tex="e^x>0" />，所以 <MathTex tex="g'(x)<0" />，<MathTex tex="g(x)" /> 在 <MathTex tex="[0,2]" /> 上单调递减。<br />最大值在左端点 <MathTex tex="x=0" /> 取得，<MathTex tex="g(0)=0" />，故 <MathTex tex="a<0" /> 时满足题意。</p></>,

  'dm3vd-1': <><p className="mt-2"><strong>解</strong>：<MathTex tex="f'(x)=2x-\dfrac{a}{x^2}=\dfrac{2x^3-a}{x^2}" />。<br />由题意，<MathTex tex="f'(x)<0" /> 在 <MathTex tex="(1,2)" /> 上有解。分母 <MathTex tex="x^2>0" /> 恒正可约，等价于 <MathTex tex="2x^3-a<0" /> 在 <MathTex tex="(1,2)" /> 上有解，移项得 <MathTex tex="a>2x^3" />，故 <MathTex tex="a>(2x^3)_{\min}" />。<br />记 <MathTex tex="g(x)=2x^3" />，<MathTex tex="g'(x)=6x^2>0" />，所以 <MathTex tex="g(x)" /> 在 <MathTex tex="(1,2)" /> 上单调递增。<br />最小值在左端点 <MathTex tex="x=1" /> 取得（端点取不到），<MathTex tex="g(1)=2" />，故 <MathTex tex="a>2" /> 时满足题意。</p></>,

  'dm3vd-2': <><p className="mt-2"><strong>解</strong>：<MathTex tex="f'(x)=x^2-1-\dfrac{a}{x^2}=\dfrac{x^4-x^2-a}{x^2}" />。<br />由题意，<MathTex tex="f'(x)>0" /> 在 <MathTex tex="(1,2)" /> 上有解。分母 <MathTex tex="x^2>0" /> 恒正可约，等价于 <MathTex tex="x^4-x^2-a>0" /> 在 <MathTex tex="(1,2)" /> 上有解，移项得 <MathTex tex="a<x^4-x^2" />，故 <MathTex tex="a<(x^4-x^2)_{\max}" />。<br />记 <MathTex tex="g(x)=x^4-x^2" />，求导得 <MathTex tex="g'(x)=4x^3-2x=2x(2x^2-1)" />。当 <MathTex tex="x\in(1,2)" /> 时，<MathTex tex="2x>0" />，<MathTex tex="2x^2-1>1>0" />，所以 <MathTex tex="g'(x)>0" />，<MathTex tex="g(x)" /> 在 <MathTex tex="(1,2)" /> 上单调递增。<br />最大值在右端点 <MathTex tex="x=2" /> 取得（端点取不到），<MathTex tex="g(2)=16-4=12" />，故 <MathTex tex="a<12" /> 时满足题意。</p></>,

  'dm3ve-1': <><p className="mt-2"><strong>解</strong>：定义域 <MathTex tex="x>0" />，<MathTex tex="f'(x)=e^x+\dfrac{a}{x}" />。<br />由题意，<MathTex tex="f'(x)<0" /> 在 <MathTex tex="(1,e)" /> 上有解，即 <MathTex tex="e^x+\dfrac{a}{x}<0" />，移项得 <MathTex tex="\dfrac{a}{x}<-e^x" />。<br />当 <MathTex tex="x\in(1,e)" /> 时 <MathTex tex="x>0" />，两边同乘 <MathTex tex="x" />，得 <MathTex tex="a<-xe^x" /> 在 <MathTex tex="(1,e)" /> 上有解，故 <MathTex tex="a<(-xe^x)_{\max}" />。<br />记 <MathTex tex="g(x)=-xe^x" />，求导得 <MathTex tex="g'(x)=-e^x-xe^x=-(x+1)e^x" />。当 <MathTex tex="x\in(1,e)" /> 时 <MathTex tex="x+1>0" />、<MathTex tex="e^x>0" />，<br />所以 <MathTex tex="g'(x)<0" />，<MathTex tex="g(x)" /> 单调递减。最大值在左端点 <MathTex tex="x=1" /> 取得（端点取不到），<MathTex tex="g(1)=-e" />，故 <MathTex tex="a<-e" /> 时满足题意。</p></>,

  'dm3ve-2': <><p className="mt-2"><strong>解</strong>：定义域 <MathTex tex="x\ne 0" />，<MathTex tex="f'(x)=e^x+\dfrac{a}{x^2}" />。<br />由题意，<MathTex tex="f'(x)<0" /> 在 <MathTex tex="(1,2)" /> 上有解，即 <MathTex tex="e^x+\dfrac{a}{x^2}<0" />，移项得 <MathTex tex="\dfrac{a}{x^2}<-e^x" />。<br />当 <MathTex tex="x\in(1,2)" /> 时 <MathTex tex="x^2>0" />，两边同乘 <MathTex tex="x^2" />，得 <MathTex tex="a<-x^2e^x" /> 在 <MathTex tex="(1,2)" /> 上有解，故 <MathTex tex="a<(-x^2e^x)_{\max}" />。<br />记 <MathTex tex="g(x)=-x^2e^x" />，求导得 <MathTex tex="g'(x)=-2xe^x-x^2e^x=-x(x+2)e^x" />。当 <MathTex tex="x\in(1,2)" /> 时 <MathTex tex="x>0" />、<MathTex tex="x+2>0" />、<MathTex tex="e^x>0" />，<br />所以 <MathTex tex="g'(x)<0" />，<MathTex tex="g(x)" /> 单调递减。最大值在左端点 <MathTex tex="x=1" /> 取得（端点取不到），<MathTex tex="g(1)=-e" />，故 <MathTex tex="a<-e" /> 时满足题意。</p></>,

  'dm3va-2': <><p className="mt-2"><strong>解</strong>：<MathTex tex="f'(x)=6x^2-6ax=6x(x-a)" />。<br />由题意，存在 <MathTex tex="x\in(1,+\infty)" />，使 <MathTex tex="f'(x)<0" />，即 <MathTex tex="6x(x-a)<0" /> 在 <MathTex tex="(1,+\infty)" /> 上有解。<br />当 <MathTex tex="x>1" /> 时 <MathTex tex="6x>0" />，两边同除 <MathTex tex="6x" />，不等号方向不变，得 <MathTex tex="x-a<0" /> 在 <MathTex tex="(1,+\infty)" /> 上有解，即 <MathTex tex="a>x" /> 有解。<br />当 <MathTex tex="x>1" /> 时 <MathTex tex="x\in(1,+\infty)" />。下面分情况讨论：<br />(i) 当 <MathTex tex="a\le 1" /> 时，对任意 <MathTex tex="x\in(1,+\infty)" />，有 <MathTex tex="x>1\ge a" />，故 <MathTex tex="a>x" /> 不成立，无解，舍。<br />(ii) 当 <MathTex tex="a>1" /> 时，取 <MathTex tex="x_0\in(1,a)" />，则 <MathTex tex="x_0<a" />，即 <MathTex tex="a>x_0" /> 成立，有解。<br />综上，<MathTex tex="a>1" /> 时满足题意。</p></>,

  // ── 1.4 锚点 0 练习 ──
  'da0-1': <><p className="mt-2"><strong>① 定义域</strong>：需 <MathTex tex="ax-1\ge 0" />，即 <MathTex tex="ax\ge 1" />。按 <MathTex tex="a" /> 分类：<br /><strong>情况一</strong> <MathTex tex="a<0" />：两边除 <MathTex tex="a" />（负数，不等号翻向），得 <MathTex tex="x\le \dfrac{1}{a}" />，定义域为 <MathTex tex="\left(-\infty,\dfrac{1}{a}\right]" />。<br /><strong>情况二</strong> <MathTex tex="a=0" />：不等式变为 <MathTex tex="-1\ge 0" />，不成立，定义域为空。<br /><strong>情况三</strong> <MathTex tex="a>0" />：两边除 <MathTex tex="a" />（正数，不等号不翻），得 <MathTex tex="x\ge \dfrac{1}{a}" />，定义域为 <MathTex tex="\left[\dfrac{1}{a},+\infty\right)" />。<br /><strong>② 求导</strong>：<MathTex tex="f'(x)=\dfrac{a}{2\sqrt{ax-1}}" />。分母 <MathTex tex="2\sqrt{ax-1}>0" /> 恒正（在定义域内部），<MathTex tex="f'" /> 的符号由分子 <MathTex tex="a" /> 决定。<br /><strong>③ 综上</strong>：<MathTex tex="a<0" /> 时 <MathTex tex="f'<0" />，<MathTex tex="f(x)" /> 在 <MathTex tex="\left(-\infty,\dfrac{1}{a}\right]" /> 上单调递减；<MathTex tex="a=0" /> 时定义域为空；<MathTex tex="a>0" /> 时 <MathTex tex="f'>0" />，<MathTex tex="f(x)" /> 在 <MathTex tex="\left[\dfrac{1}{a},+\infty\right)" /> 上单调递增。</p></>,
  'da0-2': <><p className="mt-2"><strong>① 定义域（取交集）</strong>：需同时满足 <MathTex tex="x^2-a\ge 0" /> 和 <MathTex tex="x>0" />。按 <MathTex tex="a" /> 分类：<br /><strong>情况一</strong> <MathTex tex="a\le 0" />：<MathTex tex="x^2-a\ge x^2\ge 0" /> 恒成立，只需 <MathTex tex="x>0" />，定义域为 <MathTex tex="(0,+\infty)" />。<br /><strong>情况二</strong> <MathTex tex="a>0" />：<MathTex tex="x^2\ge a" /> 且 <MathTex tex="x>0" />，得 <MathTex tex="x\ge \sqrt{a}" />，定义域为 <MathTex tex="[\sqrt{a},+\infty)" />。<br /><strong>② 求导</strong>：<MathTex tex="f'(x)=\dfrac{x}{\sqrt{x^2-a}}+\dfrac{1}{x}" />。在定义域内部 <MathTex tex="x>0" /> 且 <MathTex tex="x^2-a>0" />，两项均为正，故 <MathTex tex="f'(x)>0" /> 恒成立。<br /><strong>③ 综上</strong>：<MathTex tex="a\le 0" /> 时，<MathTex tex="f(x)" /> 在 <MathTex tex="(0,+\infty)" /> 上单调递增；<MathTex tex="a>0" /> 时，<MathTex tex="f(x)" /> 在 <MathTex tex="[\sqrt{a},+\infty)" /> 上单调递增。</p></>,

  // ── 1.4 锚点 1 练习 ──
  'da1-1': <><p className="mt-2">定义域 <MathTex tex="x>0" />。<strong>① 求导</strong>：<MathTex tex="f'(x)=\dfrac{a}{x}-1=\dfrac{a-x}{x}" />。分母 <MathTex tex="x>0" /> 恒正可约，看分子 <MathTex tex="a-x" />。零点为 <MathTex tex="x=a" />。<br /><strong>② 按 <MathTex tex="a" /> 分类</strong>：<br /><strong>情况一</strong> <MathTex tex="a\le 0" />：零点 <MathTex tex="x=a\le 0" />，不在定义域 <MathTex tex="(0,+\infty)" /> 内。定义域内 <MathTex tex="x>0\ge a" />，所以 <MathTex tex="a-x<0" />，<MathTex tex="f'(x)<0" /> 恒成立，<MathTex tex="f(x)" /> 在 <MathTex tex="(0,+\infty)" /> 上<strong>单调递减</strong>。<br /><strong>情况二</strong> <MathTex tex="a>0" />：零点 <MathTex tex="x=a>0" />，在定义域内，把 <MathTex tex="(0,+\infty)" /> 切成两段。<br /><span className="pl-4">• <MathTex tex="0<x<a" />：<MathTex tex="a-x>0" />，<MathTex tex="f'(x)>0" />，<MathTex tex="f(x)" /> 在 <MathTex tex="(0,a)" /> 上<strong>单调递增</strong>。</span><br /><span className="pl-4">• <MathTex tex="x>a" />：<MathTex tex="a-x<0" />，<MathTex tex="f'(x)<0" />，<MathTex tex="f(x)" /> 在 <MathTex tex="(a,+\infty)" /> 上<strong>单调递减</strong>。</span></p></>,
  'da1-2': <><p className="mt-2">定义域 <MathTex tex="\mathbb{R}" />。<strong>① 求导</strong>：<MathTex tex="f'(x)=e^x-a" />。零点为 <MathTex tex="e^x=a" />，即 <MathTex tex="x=\ln a" />（<MathTex tex="a>0" /> 时存在）。<br /><strong>② 按 <MathTex tex="a" /> 分类</strong>：<br /><strong>情况一</strong> <MathTex tex="a\le 0" />：因为 <MathTex tex="e^x>0" />，所以 <MathTex tex="e^x-a>0-a\ge 0" />，即 <MathTex tex="f'(x)>0" /> 恒成立，<MathTex tex="f(x)" /> 在 <MathTex tex="\mathbb{R}" /> 上<strong>单调递增</strong>。<br /><strong>情况二</strong> <MathTex tex="a>0" />：零点 <MathTex tex="x=\ln a" /> 存在，把 <MathTex tex="\mathbb{R}" /> 切成两段。<br /><span className="pl-4">• <MathTex tex="x<\ln a" />：<MathTex tex="e^x<a" />，<MathTex tex="f'(x)<0" />，<MathTex tex="f(x)" /> 在 <MathTex tex="(-\infty,\ln a)" /> 上<strong>单调递减</strong>。</span><br /><span className="pl-4">• <MathTex tex="x>\ln a" />：<MathTex tex="e^x>a" />，<MathTex tex="f'(x)>0" />，<MathTex tex="f(x)" /> 在 <MathTex tex="(\ln a,+\infty)" /> 上<strong>单调递增</strong>。</span></p></>,

  // ── 1.4 锚点 2 练习 ──
  'da2-1': <><p className="mt-2">定义域 <MathTex tex="\mathbb{R}" />。<strong>① 求导 + 因式分解</strong>：<MathTex tex="f'(x)=x^2-(a+2)x+2a=(x-2)(x-a)" />，零点为 <MathTex tex="x=2" /> 和 <MathTex tex="x=a" />。<br /><strong>② 按 <MathTex tex="a" /> 与 <MathTex tex="2" /> 的大小分类</strong>：<br /><strong>情况一</strong> <MathTex tex="a>2" />：<MathTex tex="2<a" />，分段 <MathTex tex="(-\infty,2)" />、<MathTex tex="(2,a)" />、<MathTex tex="(a,+\infty)" />。<br /><span className="pl-4">• <MathTex tex="x<2" />：<MathTex tex="x-2<0" />，<MathTex tex="x-a<0" />，负 × 负 = 正，<MathTex tex="f'(x)>0" />，<strong>单调递增</strong>。</span><br /><span className="pl-4">• <MathTex tex="2<x<a" />：<MathTex tex="x-2>0" />，<MathTex tex="x-a<0" />，异号，<MathTex tex="f'(x)<0" />，<strong>单调递减</strong>。</span><br /><span className="pl-4">• <MathTex tex="x>a" />：两正相乘 = 正，<MathTex tex="f'(x)>0" />，<strong>单调递增</strong>。</span><br /><strong>情况二</strong> <MathTex tex="a=2" />（重根）：<MathTex tex="f'(x)=(x-2)^2\ge 0" /> 恒成立，<MathTex tex="f(x)" /> 在 <MathTex tex="\mathbb{R}" /> 上<strong>单调递增</strong>。<br /><strong>情况三</strong> <MathTex tex="a<2" />：<MathTex tex="a<2" />，分段 <MathTex tex="(-\infty,a)" />、<MathTex tex="(a,2)" />、<MathTex tex="(2,+\infty)" />。<br /><span className="pl-4">• <MathTex tex="x<a" />：<MathTex tex="x-2<0" />，<MathTex tex="x-a<0" />，负 × 负 = 正，<MathTex tex="f'(x)>0" />，<strong>单调递增</strong>。</span><br /><span className="pl-4">• <MathTex tex="a<x<2" />：<MathTex tex="x-2<0" />，<MathTex tex="x-a>0" />，异号，<MathTex tex="f'(x)<0" />，<strong>单调递减</strong>。</span><br /><span className="pl-4">• <MathTex tex="x>2" />：两正相乘 = 正，<MathTex tex="f'(x)>0" />，<strong>单调递增</strong>。</span></p></>,
  'da2-2': <><p className="mt-2">定义域 <MathTex tex="\mathbb{R}" />。<strong>① 求导 + 因式分解</strong>：<MathTex tex="f'(x)=x^2-3ax+2a^2=(x-a)(x-2a)" />，零点为 <MathTex tex="x=a" /> 和 <MathTex tex="x=2a" />，<strong>都含参</strong>。<br /><strong>② 比较两根</strong>：<MathTex tex="2a-a=a" />，差的符号 = <MathTex tex="a" /> 的符号，按 <MathTex tex="a" /> 符号分类。<br /><strong>情况一</strong> <MathTex tex="a>0" />：<MathTex tex="a<2a" />，分段 <MathTex tex="(-\infty,a)" />、<MathTex tex="(a,2a)" />、<MathTex tex="(2a,+\infty)" />。<br /><span className="pl-4">• <MathTex tex="x<a" />：<MathTex tex="x-a<0" />，<MathTex tex="x-2a<0" />，负 × 负 = 正，<MathTex tex="f'(x)>0" />，<strong>单调递增</strong>。</span><br /><span className="pl-4">• <MathTex tex="a<x<2a" />：<MathTex tex="x-a>0" />，<MathTex tex="x-2a<0" />，异号，<MathTex tex="f'(x)<0" />，<strong>单调递减</strong>。</span><br /><span className="pl-4">• <MathTex tex="x>2a" />：两正相乘 = 正，<MathTex tex="f'(x)>0" />，<strong>单调递增</strong>。</span><br /><strong>情况二</strong> <MathTex tex="a=0" />（重根）：<MathTex tex="f'(x)=x^2\ge 0" /> 恒成立，<MathTex tex="f(x)" /> 在 <MathTex tex="\mathbb{R}" /> 上<strong>单调递增</strong>。<br /><strong>情况三</strong> <MathTex tex="a<0" />：<MathTex tex="2a<a" />，分段 <MathTex tex="(-\infty,2a)" />、<MathTex tex="(2a,a)" />、<MathTex tex="(a,+\infty)" />。<br /><span className="pl-4">• <MathTex tex="x<2a" />：<MathTex tex="x-a<0" />（因 <MathTex tex="x<2a<a" />），<MathTex tex="x-2a<0" />，负 × 负 = 正，<MathTex tex="f'(x)>0" />，<strong>单调递增</strong>。</span><br /><span className="pl-4">• <MathTex tex="2a<x<a" />：<MathTex tex="x-a<0" />，<MathTex tex="x-2a>0" />，异号，<MathTex tex="f'(x)<0" />，<strong>单调递减</strong>。</span><br /><span className="pl-4">• <MathTex tex="x>a" />：<MathTex tex="x-a>0" />，<MathTex tex="x-2a>0" />（因 <MathTex tex="x>a>2a" />），两正相乘 = 正，<MathTex tex="f'(x)>0" />，<strong>单调递增</strong>。</span></p></>,

  // ── 1.4 锚点 3 练习 ──
  'da3-1': <><p className="mt-2"><strong>① 定义域 + 求导</strong>：定义域 <MathTex tex="x>0" />。求导通分得 <MathTex tex="f'(x)=x-2a+\dfrac{1}{x}=\dfrac{x^2-2ax+1}{x}" />。<br /><strong>② 分析</strong>：分母 <MathTex tex="x>0" /> 恒正，符号由分子 <MathTex tex="g(x)=x^2-2ax+1" /> 决定（开口向上）。判别式 <MathTex tex="\Delta=4a^2-4=4(a^2-1)" />。<br /><strong>③ 按 <MathTex tex="\Delta" /> 分类</strong>：<br /><strong>情况一</strong> <MathTex tex="\Delta\le 0" />（即 <MathTex tex="-1\le a\le 1" />）：开口向上，<MathTex tex="g(x)\ge 0" /> 恒成立，<MathTex tex="f'(x)\ge 0" />，<MathTex tex="f(x)" /> 在 <MathTex tex="(0,+\infty)" /> 上<strong>单调递增</strong>。<br /><strong>情况二</strong> <MathTex tex="\Delta>0" /> 且 <MathTex tex="a<-1" />：韦达定理：和 <MathTex tex="=2a" />，积 <MathTex tex="=1" />。积为正，看和，因为 <MathTex tex="a<-1" />，所以和 <MathTex tex="2a<-2<0" />，两根<strong>都为负</strong>，都在定义域外。定义域内 <MathTex tex="x>0>x_2>x_1" />，<MathTex tex="x-x_1>0" />、<MathTex tex="x-x_2>0" />，<MathTex tex="g(x)>0" />，<MathTex tex="f'(x)>0" />，<MathTex tex="f(x)" /> 在 <MathTex tex="(0,+\infty)" /> 上<strong>单调递增</strong>。<br /><strong>情况三</strong> <MathTex tex="\Delta>0" /> 且 <MathTex tex="a>1" />：积 <MathTex tex="=1>0" />、和 <MathTex tex="=2a>2>0" />，两根<strong>都为正</strong>，都在定义域内。设 <MathTex tex="x_1<x_2" />，因式分解 <MathTex tex="g(x)=(x-x_1)(x-x_2)" />，把 <MathTex tex="(0,+\infty)" /> 切成 <MathTex tex="(0,x_1)" />、<MathTex tex="(x_1,x_2)" />、<MathTex tex="(x_2,+\infty)" />。<br /><span className="pl-4">• <MathTex tex="(0,x_1)" />：<MathTex tex="x-x_1<0" />、<MathTex tex="x-x_2<0" />，相乘为正，<MathTex tex="f'(x)>0" />，<strong>单调递增</strong>；</span><br /><span className="pl-4">• <MathTex tex="(x_1,x_2)" />：异号，<MathTex tex="f'(x)<0" />，<strong>单调递减</strong>；</span><br /><span className="pl-4">• <MathTex tex="(x_2,+\infty)" />：两正相乘，<MathTex tex="f'(x)>0" />，<strong>单调递增</strong>。</span><br /><strong>④ 综上所述</strong>：<MathTex tex="a\le 1" /> 时，<MathTex tex="f(x)" /> 在 <MathTex tex="(0,+\infty)" /> 上单调递增；<MathTex tex="a>1" /> 时，增区间 <MathTex tex="(0,x_1)" /> 和 <MathTex tex="(x_2,+\infty)" />，减区间 <MathTex tex="(x_1,x_2)" />，其中 <MathTex tex="x_1=a-\sqrt{a^2-1}" />，<MathTex tex="x_2=a+\sqrt{a^2-1}" />。</p></>,
  'da3-2': <><p className="mt-2"><strong>① 定义域 + 求导</strong>：定义域 <MathTex tex="x>0" />。求导通分得 <MathTex tex="f'(x)=x+a-\dfrac{2}{x}=\dfrac{x^2+ax-2}{x}" />。<br /><strong>② 分析</strong>：分母 <MathTex tex="x>0" /> 恒正，符号由分子 <MathTex tex="g(x)=x^2+ax-2" /> 决定（开口向上）。判别式 <MathTex tex="\Delta=a^2+8>0" /> 恒成立，<strong>无需按 <MathTex tex="\Delta" /> 分类</strong>。<br /><strong>③ 由韦达定理判两根位置</strong>：和 <MathTex tex="=-a" />，积 <MathTex tex="=-2<0" />，两根<strong>异号</strong>（一正一负）。设 <MathTex tex="x_1<x_2" />，则 <MathTex tex="x_1<0<x_2" />，即 <MathTex tex="x_1" /> 在定义域外、<MathTex tex="x_2" /> 在定义域内（<strong>一内一外</strong>）。<br /><strong>④ 用域内根 <MathTex tex="x_2" /> 分段</strong>：因式分解 <MathTex tex="g(x)=(x-x_1)(x-x_2)" />。在 <MathTex tex="(0,+\infty)" /> 上，<MathTex tex="x>0>x_1" />，所以 <MathTex tex="x-x_1>0" /> 恒正（不变号），符号由 <MathTex tex="x-x_2" /> 决定。<br /><span className="pl-4">• <MathTex tex="(0,x_2)" />：<MathTex tex="x-x_2<0" />，<MathTex tex="g(x)<0" />，<MathTex tex="f'(x)<0" />，<strong>单调递减</strong>；</span><br /><span className="pl-4">• <MathTex tex="(x_2,+\infty)" />：<MathTex tex="x-x_2>0" />，<MathTex tex="g(x)>0" />，<MathTex tex="f'(x)>0" />，<strong>单调递增</strong>。</span><br /><strong>⑤ 综上所述</strong>：<MathTex tex="f(x)" /> 在 <MathTex tex="(0,x_2)" /> 上单调递减，在 <MathTex tex="(x_2,+\infty)" /> 上单调递增，其中 <MathTex tex="x_2=\dfrac{-a+\sqrt{a^2+8}}{2}" />。</p></>,
};

export function DerivativeApplication2Answers() {
  return (
    <section className="print-answers">
      <PageBreak label="答案与解析" />
      <h2 className="text-xl font-bold text-gray-900 mb-4">📝 3.6 导数应用（下） — 答案与解析</h2>
      <div className="space-y-2 text-[0.95rem]">
        {Object.entries(derivativeApplication2Explanations).map(([id, expl]) => (
          <div key={id} className="border-b border-gray-200 pb-1">
            <span className="font-bold text-gray-800 mr-2">{id}</span>
            {expl}
          </div>
        ))}
      </div>
    </section>
  );
}
