import { Math as MathTex, PageBreak } from '@/components/shared';

export const closedMaxExplanations: Record<string, React.ReactNode> = {
  // ── 闭区间最值练习解析 ──
  'dmax-1': <><p className="mt-2"><strong>定义域</strong>：<MathTex tex="\mathbb{R}" />，区间 <MathTex tex="[-1,4]" /> 完全包含 ✓<br /><strong>求驻点</strong>：<MathTex tex="f'(x)=3x^2-6x=3x(x-2)" />，令 <MathTex tex="f'(x)=0" /> 得 <MathTex tex="x=0" />、<MathTex tex="x=2" />（均在 <MathTex tex="(-1,4)" /> 内 ✓）<br /><strong>候选清单</strong>：驻点 <MathTex tex="0,2" /> + 端点 <MathTex tex="-1,4" />，共 4 个候选点。<br /><strong>代入 <MathTex tex="f(x)" /></strong>（不是 <MathTex tex="f'" />）：<br /><span className="pl-2"><MathTex tex="f(-1)=-1-3=-4" /></span><br /><span className="pl-2"><MathTex tex="f(0)=0" />（极大值）</span><br /><span className="pl-2"><MathTex tex="f(2)=8-12=-4" />（极小值）</span><br /><span className="pl-2"><MathTex tex="f(4)=64-48=16" /></span><br /><strong>比较</strong>：<MathTex tex="\{-4,\,0,\,-4,\,16\}" />。<br /><strong>结论</strong>：<strong>最大值 16</strong>（在端点 <MathTex tex="x=4" /> 取得），<strong>最小值 -4</strong>（在端点 <MathTex tex="x=-1" /> 和极小值点 <MathTex tex="x=2" /> 同时取得）。<br /><span className="text-red-700"><strong>⚠️ 教学点</strong>：极大值 0 不是最大值（端点 <MathTex tex="f(4)=16" /> 更大）；最小值可在多个点同时取得（数值唯一即可）。</span></p></>,
  'dmax-2': <><p className="mt-2"><strong>定义域</strong>：<MathTex tex="\mathbb{R}" />，区间 <MathTex tex="[0,2]" /> 完全包含 ✓<br /><strong>求驻点</strong>：<MathTex tex="f'(x)=3x^2-3=3(x-1)(x+1)" />，令 <MathTex tex="f'(x)=0" /> 得 <MathTex tex="x=\pm 1" />。<br /><span className="text-red-700"><strong>⚠️ 只保留落在 <MathTex tex="(0,2)" /> 内的驻点</strong>：<MathTex tex="x=1" /> 在区间内 ✓ 保留；<MathTex tex="x=-1" /> 不在区间内 ✗ 舍去。</span><br /><strong>候选清单</strong>：驻点 <MathTex tex="1" /> + 端点 <MathTex tex="0,2" />，共 3 个候选点。<br /><strong>代入 <MathTex tex="f(x)" /></strong>：<br /><span className="pl-2"><MathTex tex="f(0)=0-0+1=1" /></span><br /><span className="pl-2"><MathTex tex="f(1)=1-3+1=-1" />（极小值）</span><br /><span className="pl-2"><MathTex tex="f(2)=8-6+1=3" /></span><br /><strong>比较</strong>：<MathTex tex="\{1,\,-1,\,3\}" />。<br /><strong>结论</strong>：<strong>最大值 3</strong>（在端点 <MathTex tex="x=2" /> 取得），<strong>最小值 -1</strong>（在驻点 <MathTex tex="x=1" /> 取得）。<br /><span className="text-red-700"><strong>⚠️ 教学点</strong>：驻点 <MathTex tex="x=-1" /> 不在区间内，<strong>不参与比较</strong>；本题最大值在端点取得，不是驻点。</span></p></>,
  'cmax1-1': <><p className="mt-2"><strong>定义域</strong>：<MathTex tex="\mathbb{R}" />，区间 <MathTex tex="[-2,3]" /> 完全包含 ✓<br /><strong>求驻点</strong>：<MathTex tex="f'(x)=6x^2-6x-12=6(x-2)(x+1)" />，令 <MathTex tex="f'(x)=0" /> 得 <MathTex tex="x=-1" />、<MathTex tex="x=2" />（均在 <MathTex tex="(-2,3)" /> 内 ✓）<br /><strong>候选清单</strong>：驻点 <MathTex tex="-1,2" /> + 端点 <MathTex tex="-2,3" />，共 4 个候选点。<br /><strong>代入 <MathTex tex="f(x)" /></strong>：<br /><span className="pl-2"><MathTex tex="f(-2)=-16-12+24+5=1" /></span><br /><span className="pl-2"><MathTex tex="f(-1)=-2-3+12+5=12" />（极大值）</span><br /><span className="pl-2"><MathTex tex="f(2)=16-12-24+5=-15" />（极小值）</span><br /><span className="pl-2"><MathTex tex="f(3)=54-27-36+5=-4" /></span><br /><strong>比较</strong>：<MathTex tex="\{1,\,12,\,-15,\,-4\}" />。<br /><strong>结论</strong>：<strong>最大值 12</strong>（在驻点 <MathTex tex="x=-1" /> 取得），<strong>最小值 -15</strong>（在驻点 <MathTex tex="x=2" /> 取得）。<br /><span className="text-red-700"><strong>⚠️ 教学点</strong>：本题最大值和最小值都在驻点取得，端点 <MathTex tex="f(-2)=1" />、<MathTex tex="f(3)=-4" /> 均不是最值——再次说明<strong>必须把端点也放进候选清单一起比较</strong>，不能只看驻点。</span></p></>,
  'cmax2-1': <><p className="mt-2"><strong>定义域</strong>：<MathTex tex="\ln x" /> 要求 <MathTex tex="x>0" />，区间 <MathTex tex="[1,e^2]" /> 完全包含 ✓<br /><strong>求驻点</strong>（商法则）：<MathTex tex="f'(x)=\dfrac{(\ln x)'\cdot x-\ln x\cdot x'}{x^2}=\dfrac{1-\ln x}{x^2}" />。分母 <MathTex tex="x^2>0" /> 恒正可约，看分子 <MathTex tex="1-\ln x" />。令 <MathTex tex="1-\ln x=0" />，<MathTex tex="\ln x=1" />，得驻点 <MathTex tex="x=e" />（在 <MathTex tex="(1,e^2)" /> 内 ✓ 保留）。<br /><strong>判单调性</strong>（看分子 <MathTex tex="1-\ln x" />）：在 <MathTex tex="(1,e)" /> 内 <MathTex tex="\ln x<1" />，<MathTex tex="1-\ln x>0" />，<MathTex tex="f'>0" /> → <strong>递增</strong>；在 <MathTex tex="(e,e^2)" /> 内 <MathTex tex="\ln x>1" />，<MathTex tex="1-\ln x<0" />，<MathTex tex="f'<0" /> → <strong>递减</strong>。<br /><strong>用单调性定最值</strong>：先增后减 → <strong>极大值就是最大值</strong>，<MathTex tex="\max=f(e)=\dfrac{\ln e}{e}=\dfrac{1}{e}" />，无需比较。<br /><strong>最小值在两端点中</strong>：<MathTex tex="f(1)=\dfrac{\ln 1}{1}=0" />，<MathTex tex="f(e^2)=\dfrac{\ln e^2}{e^2}=\dfrac{2}{e^2}" />。因 <MathTex tex="\dfrac{2}{e^2}>0" />（分子分母都为正），所以 <MathTex tex="\min=f(1)=0" />。<br /><strong>结论</strong>：<strong>最大值 <MathTex tex="\dfrac{1}{e}" /></strong>（在驻点 <MathTex tex="x=e" /> 取得），<strong>最小值 0</strong>（在左端点 <MathTex tex="x=1" /> 取得）。</p></>,
  'cmax3-1': <><p className="mt-2"><strong>定义域</strong>：<MathTex tex="\mathbb{R}" />，区间 <MathTex tex="[-2,1]" /> 完全包含 ✓<br /><strong>求驻点</strong>（乘积法则）：<MathTex tex="f'(x)=(x)'\cdot e^x+x\cdot(e^x)'=e^x+xe^x=(1+x)e^x" />。<MathTex tex="e^x>0" /> 恒正可约，看 <MathTex tex="1+x" />。令 <MathTex tex="1+x=0" /> 得驻点 <MathTex tex="x=-1" />（在 <MathTex tex="(-2,1)" /> 内 ✓ 保留）。<br /><strong>判单调性</strong>（看 <MathTex tex="1+x" />）：在 <MathTex tex="(-2,-1)" /> 内 <MathTex tex="1+x<0" />，<MathTex tex="f'(x)<0" /> → <MathTex tex="f(x)" /> <strong>递减</strong>；在 <MathTex tex="(-1,1)" /> 内 <MathTex tex="1+x>0" />，<MathTex tex="f'(x)>0" /> → <MathTex tex="f(x)" /> <strong>递增</strong>。<br /><strong>用单调性定最值</strong>：先减后增 → <MathTex tex="f(-1)" /> 是谷底 → <MathTex tex="\min=f(-1)=-1\cdot e^{-1}=-\dfrac{1}{e}" />。<br /><strong>最大值在两端点中</strong>：<MathTex tex="f(-2)=-2e^{-2}=-\dfrac{2}{e^2}<0" />，<MathTex tex="f(1)=1\cdot e^1=e>0" />，故 <MathTex tex="\max=f(1)=e" />。<br /><strong>结论</strong>：<strong>最大值 <MathTex tex="e" /></strong>（在 <MathTex tex="x=1" /> 处取得），<strong>最小值 <MathTex tex="-\dfrac{1}{e}" /></strong>（在 <MathTex tex="x=-1" /> 处取得）。</p></>,
  'cmax4-1': <><p className="mt-2"><strong>① 定义域</strong>：<MathTex tex="\mathbb{R}" />，区间 <MathTex tex="[0,2]" /> 完全包含 ✓<br /><strong>② 求导找驻点</strong>：<MathTex tex="f'(x)=3x^2-3a=3(x^2-a)" />。提出 3 恒正可约，看因子 <MathTex tex="x^2-a" /> 的正负就能定 <MathTex tex="f'(x)" /> 正负。令 <MathTex tex="x^2-a=0" />，得 <MathTex tex="x=\pm\sqrt{a}" />。因为 <MathTex tex="\sqrt{a}\ge 0" />（根号恒非负），所以 <MathTex tex="-\sqrt{a}\le 0" /> 不在区间内，舍去；区间 <MathTex tex="[0,2]" /> 内只看 <MathTex tex="x=\sqrt{a}" />。<br /><strong>③ 按 <MathTex tex="a" /> 与 <MathTex tex="x^2" /> 在区间上的关系分类讨论</strong>：因为 <MathTex tex="x=\sqrt{a}" />，同时平方得 <MathTex tex="x^2=a" />。又因 <MathTex tex="x\in[0,2]" />，所以 <MathTex tex="x^2\in[0,4]" />。<br /><strong>情况一：当 <MathTex tex="a" /> 在区间左边时，即 <MathTex tex="a\le 0" /> 时</strong>。结合 <MathTex tex="x^2\ge 0" />（因 <MathTex tex="x^2\in[0,4]" />），得 <MathTex tex="a\le 0\le x^2" />，移项得 <MathTex tex="x^2-a\ge 0" />。所以 <MathTex tex="f'(x)=3(x^2-a)\ge 0" />，<MathTex tex="f(x)" /> <strong>单调递增</strong>，最小值在左端点，<MathTex tex="\min=f(0)=0" />。<br /><strong>情况二：当 <MathTex tex="a" /> 在区间内部时，即 <MathTex tex="0<a<4" /></strong>。即 <MathTex tex="0<\sqrt{a}<2" />，含参驻点 <MathTex tex="\sqrt{a}" /> 把区间分为 <MathTex tex="(0,\sqrt{a})" /> 和 <MathTex tex="(\sqrt{a},2)" /> 两段：当 <MathTex tex="0<x<\sqrt{a}" /> 时，<MathTex tex="x^2<a" />，<MathTex tex="x^2-a<0" />，在 <MathTex tex="(0,\sqrt{a})" /> 上 <MathTex tex="f'(x)<0" />，<strong>单调递减</strong>；当 <MathTex tex="\sqrt{a}<x<2" /> 时，<MathTex tex="x^2>a" />，<MathTex tex="x^2-a>0" />，在 <MathTex tex="(\sqrt{a},2)" /> 上 <MathTex tex="f'(x)>0" />，<strong>单调递增</strong>。先减后增，<MathTex tex="x=\sqrt{a}" /> 处为谷底，<MathTex tex="\min=f(\sqrt{a})=(\sqrt{a})^3-3a\sqrt{a}=a\sqrt{a}-3a\sqrt{a}=-2a\sqrt{a}" />。<br /><strong>情况三：当 <MathTex tex="a" /> 在区间右边时，即 <MathTex tex="a\ge 4" /> 时</strong>。结合 <MathTex tex="x^2\le 4" />（因 <MathTex tex="x^2\in[0,4]" />），得 <MathTex tex="x^2\le 4\le a" />，移项得 <MathTex tex="x^2-a\le 0" />。所以 <MathTex tex="f'(x)=3(x^2-a)\le 0" />，<MathTex tex="f(x)" /> <strong>单调递减</strong>，最小值在右端点，<MathTex tex="\min=f(2)=8-6a" />。<br /><strong>④ 综上所述</strong>：<MathTex tex="a\le 0" /> 时 <MathTex tex="\min=0" />；<MathTex tex="0<a<4" /> 时 <MathTex tex="\min=-2a\sqrt{a}" />；<MathTex tex="a\ge 4" /> 时 <MathTex tex="\min=8-6a" />。</p></>,
  'cmax3-2': <><p className="mt-2"><strong>定义域</strong>：<MathTex tex="\mathbb{R}" />，区间 <MathTex tex="[0,1]" /> 完全包含 ✓<br /><strong>求驻点</strong>（链式法则，<MathTex tex="(e^{2x})'=e^{2x}\cdot 2=2e^{2x}" />）：<MathTex tex="f'(x)=2e^{2x}-4" />。令 <MathTex tex="f'(x)=0" />，即 <MathTex tex="2e^{2x}=4" />，<MathTex tex="e^{2x}=2" />，化为对数形式 <MathTex tex="2x=\log_e 2=\ln 2" />，得驻点 <MathTex tex="x=\dfrac{\ln 2}{2}" />。<br /><strong>验证驻点在区间内</strong>：因 <MathTex tex="\ln 1<\ln 2<\ln e" />，得 <MathTex tex="0<\ln 2<1" />，所以 <MathTex tex="0<\dfrac{\ln 2}{2}<\dfrac{1}{2}" /> ✓ 保留。<br /><strong>判单调性</strong>（<MathTex tex="e^{2x}" /> 单调递增）：在 <MathTex tex="\left(0,\tfrac{\ln 2}{2}\right)" /> 内 <MathTex tex="e^{2x}<2" />，<MathTex tex="f'(x)<0" />，<MathTex tex="f(x)" /> <strong>递减</strong>；在 <MathTex tex="\left(\tfrac{\ln 2}{2},1\right)" /> 内 <MathTex tex="e^{2x}>2" />，<MathTex tex="f'(x)>0" />，<MathTex tex="f(x)" /> <strong>递增</strong>。<br /><strong>用单调性定最值</strong>：先减后增 → <MathTex tex="f\left(\tfrac{\ln 2}{2}\right)" /> 是谷底 → <MathTex tex="\min=e^{2\cdot\frac{\ln 2}{2}}-4\cdot\dfrac{\ln 2}{2}=e^{\ln 2}-2\ln 2=2-2\ln 2" />。<br /><strong>最大值在两端点中</strong>：<MathTex tex="f(0)=e^0-0=1" />，<MathTex tex="f(1)=e^2-4\approx 3.39" />，故 <MathTex tex="\max=f(1)=e^2-4" />。<br /><strong>结论</strong>：<strong>最大值 <MathTex tex="e^2-4" /></strong>（在 <MathTex tex="x=1" /> 处取得），<strong>最小值 <MathTex tex="2-2\ln 2" /></strong>（在 <MathTex tex="x=\dfrac{\ln 2}{2}" /> 处取得）。</p></>,
};

export function ClosedMaxAnswers() {
  return (
    <section className="print-answers">
      <PageBreak label="答案与解析" />
      <h2 className="text-xl font-bold text-gray-900 mb-4">📝 3.6.3 闭区间最值 — 答案与解析</h2>
      <div className="space-y-2 text-[0.95rem]">
        {Object.entries(closedMaxExplanations).map(([id, expl]) => (
          <div key={id} className="border-b border-gray-200 pb-1">
            <span className="font-bold text-gray-800 mr-2">{id}</span>
            {expl}
          </div>
        ))}
      </div>
    </section>
  );
}
